### PR TITLE
Add class constructors taking STL container types, primarily for Python use

### PR DESCRIPTION
**Pull request by ferdnyc**
#### Update 2
I finally solved the (for me) holy grail:
```python3
>>> import openshot
>>> f = openshot.Fraction(30000, 1001)
>>> dict(f)
# The "10001" that used to be here was a typo
{'den': 1001, 'num': 30000}
>>> f["num"]
30000
>>> f["den"]
1001
```
Which makes Fraction _hugely_ flexible, because now we can _almost_ store it **directly** in Python data types and access it transparently as if it's a `dict`:
```python
>>> data = {}
>>> data.update({"fps": openshot.Fraction(30000, 1001)})
>>> data
{'fps': Fraction(30000, 1001)}
>>> data["fps"]
Fraction(30000, 1001)
>>> data["fps"]["num"]
30000
>>> data["fps"]["den"]
1001
```
The "almost" comes about because `data` above isn't serializable:
```python
>>> import json
>>> json.dumps(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Fraction is not JSON serializable
```
But it doesn't stop us from doing this:
```python3
>>> data = {}
>>> data.update({"fps": dict(openshot.Fraction(30000, 1001))})
>>> data
{'fps': {'den': 1001, 'num': 30000}}
```

#### Update
I added STL container constructors to various other OpenShot data types, including Coordinate, Point, and Keyframe. Coordinate now accepts a `std::pair` tuple, and `Keyframe` will accept a `std::vector<>` of either `openshot::Point` or `openshot::Coordinate`, and build its keyframe list from that.

You still can't do this, Python isn't that smart:
```python
>>> kf = openshot.Keyframe([(1, 1), (2, 2), (3, 3)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bindings/python/openshot.py", line 2728, in __init__
    _openshot.Keyframe_swiginit(self, _openshot.new_Keyframe(*args))
TypeError: Wrong number or type of arguments for overloaded function 'new_Keyframe'.
  Possible C/C++ prototypes are:
    openshot::Keyframe::Keyframe()
    openshot::Keyframe::Keyframe(double)
    openshot::Keyframe::Keyframe(openshot::Keyframe::PointsVector const &)
    openshot::Keyframe::Keyframe(openshot::Keyframe::CoordinateVector const &)
```

But you _can_ use the existing `PointsVector` and `CoordinateVector` template specializations defined in the bindings to do things like this:
```python
>>> points = [(1, 1), (2, 2), (3, 3)]
>>> cvec = openshot.CoordinateVector([openshot.Coordinate(c) for c in points])
>>> kf = openshot.Keyframe(cvec)
>>> kf.PrintPoints()
1.0000	1.0000
2.0000	2.0000
3.0000	3.0000
```

### Original description
Ever felt `openshot.Fraction()` was kind of inflexible, with its _two_ positional integer arguments?

#### Before 

```python3
>>> import openshot
#
# Sure, this works...
#
>>> openshot.Fraction(30, 1)
30:1
#
# But  what if you have a list? A tuple? A dict?
#
>>> openshot.Fraction([30, 1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ferd/rpmbuild/REPOS/libopenshot/build/bindings/python/openshot.py", line 1883, in __init__
    _openshot.Fraction_swiginit(self, _openshot.new_Fraction(*args))
TypeError: Wrong number or type of arguments for overloaded function 'new_Fraction'.
  Possible C/C++ prototypes are:
    openshot::Fraction::Fraction()
    openshot::Fraction::Fraction(int,int)

>>> openshot.Fraction((30, 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ferd/rpmbuild/REPOS/libopenshot/build/bindings/python/openshot.py", line 1883, in __init__
    _openshot.Fraction_swiginit(self, _openshot.new_Fraction(*args))
TypeError: Wrong number or type of arguments for overloaded function 'new_Fraction'.
  Possible C/C++ prototypes are:
    openshot::Fraction::Fraction()
    openshot::Fraction::Fraction(int,int)

#
# Bleah.
# I mean, sure, you could do this, but... ick
#
>>> fps = (30, 1)
>>> openshot.Fraction(*fps)
30:1
# Fraction's just kind of a downer. *sad_trombone*
```

Well, fret no more, because `openshot.Fraction()` **NOW SPEAKS CONTAINER ARGS**!

#### After

```python3
>>> import openshot
#
# This still works, same as always (I did change the __repr__, tho.)
#
>>> openshot.Fraction(30, 1)
Fraction(30, 1)
# 
# But now, hold on to your socks, kiddies...
#
# Tuples!
#
>>> openshot.Fraction((24, 1))
Fraction(24, 1)
#
# Lists of any length >= 2!
#
>>> openshot.Fraction([24000, 1001, 86, 75, 309])
Fraction(24000, 1001)
#
# And... *drumroll*... dicts!
#
>>> f = openshot.Fraction({"num": 30000, "den": 1001})
>>> f
Fraction(30000, 1001)
>>> f.Reciprocal()
Fraction(1001, 30000)
>>> f.ToFloat()
29.970029830932617
# 
# In both directions! (This has actually been there for months, though...)
#
>>> f.GetMap()
{'den': 1001, 'num': 30000}
#
# If either or both of the necessary keys is missing, that argument defaults to 0
#
>>> openshot.Fraction({"red": 1, "blue": 2})
Fraction(0, 0)
>>> openshot.Fraction({"num": 1, "blue": 2})
Fraction(1, 0)
```

All joking aside, hopefully the utility of those _last_ few of examples is obvious.

```python3
# Now, instead of having to write roundabout Python like:
frame_rate = app.project.get("fps")
fps = openshot.Fraction(frame_rate.get("num"), frame_rate.get("den"))

# We can just write
fps = openshot.Fraction(app.project.get("fps"))
```

C++ unit test coverage is included for all of the added constructors. (And one last commit that just shuffles around a bunch of unrelated `#include`s, because I can't help myself.)

### CODE REVIEW

**Comment by ferdnyc** [comment]
I should probably point out that, while I only showed these off in Python, the new constructors are implemented in C++ on top of `std::pair<int, int>`, `std::vector<int>`, and `std::map<std::string, int>`, and they can equally be used that way from C++ or any other compatible binding. It's all SWIG's automatic type conversion that makes them work in Python.

The new unit tests demonstrates how they'd be used from C++.

**Comment by ferdnyc** [comment]
And, I threw in a set of `Coordinate` unit tests to get coverage to 100%, because it was _so_ close.

**Comment by ferdnyc** [comment]
Fun fact: I had originally added additional container-accepting constructors, like:
```c++
# std::pair construction for openshot::Point
Point::Point(const std::pair<double, double>& co);
# std::pair vector construction for openshot::Keyframe
Keyframe::Keyframe(const std::vector<std::pair<double, double>>& points);
```
But I had to take those out, because not only did they _not_ make the Python any more flexible (like, the second one didn't make `openshot.Keyframe([(1, 1), (2, 2)])` work), they made the C++ ambiguous.

The `Keyframe(std::vector<Coordinate>)` constructor can _already_ "effectively" accept a `std::vector<std::pair<double, double>>`, via the `std::vector<Coordinate>` overload and `Coordinate`'s own `std::pair<>` constructor.

**Comment by jonoomph** [comment]
@ferdnyc This looks awesome! Nice work!!! I'm itching to merge this one as well, but we have some conflicts.

**Comment by ferdnyc** [comment]
@jonoomph Conflicts resolved, and even _more_ flexibility added to `openshot.Fraction` by making the coercion to Python `dict` fully transparent. (See "Update 2" added to the OP.)

**Comment by ferdnyc** [comment]
> The "almost" comes about because `data` above isn't serializable:
> 
> ```python
> >>> import json
> >>> json.dumps(data)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib64/python3.9/json/__init__.py", line 231, in dumps
>     return _default_encoder.encode(obj)
>   File "/usr/lib64/python3.9/json/encoder.py", line 199, in encode
>     chunks = self.iterencode(o, _one_shot=True)
>   File "/usr/lib64/python3.9/json/encoder.py", line 257, in iterencode
>     return _iterencode(o, 0)
>   File "/usr/lib64/python3.9/json/encoder.py", line 179, in default
>     raise TypeError(f'Object of type {o.__class__.__name__} '
> TypeError: Object of type Fraction is not JSON serializable
> ```

This can pretty easily be corrected, BTW, if we define a custom encoder class. Which can be a simple subclass of `json.JSONEncoder` with support for extra types patched in to its `.default()` method, e.g.:
```python
>>> class OurEncoder(json.JSONEncoder):
...     def default(self, o):
...         if isinstance(o, openshot.Fraction):
...             return dict(o)
...         return super().default(o)
... 
>>> data = {}; data.update({"fps": openshot.Fraction(30000, 1001)})
>>> data
{'fps': Fraction(30000, 1001)}
>>> json.dumps(data, cls=OurEncoder)
'{"fps": {"den": 1001, "num": 30000}}'
```

But if we wanted bidirectionality, getting `json.loads()` to convert the JSON `fps` object _into_ an `openshot.Fraction()` on the way in would be trickier.

**Comment by jonoomph** [comment]
Sounds awesome! Thanks for resolving the conflicts. I'm gonna merge this one now. 👍

**Pull request merged**
