### PR TITLE
Use std::make_shared to allocate shared ptrs, instead of std::shared_ptr constructors

### PR DESCRIPTION
**Pull request by ferdnyc**
std::make_shared does in a single allocation what the constructors for std::shared_ptr usually take at least 2 allocations to do.

```cpp
//
// This PR replaces instances of shared-pointer allocations like:
//
std::shared_ptr<Type> name = std::shared_ptr<Type>(new Type(...));
name = std::shared_ptr<Type>(new Type(...));
std::shared_ptr<Type> name(new Type(...));
//
// with calls to the make_shared factory function, e.g:
//
auto name = std::make_shared<Type>(...);
name = std::make_shared<Type>(...);
```
As you can see, the revised syntax is at worst as concise, and in some cases much _more_ concise, than the previous code. And, doing this may give us an infinitesimal performance/memory improvement (though I don't expect it's measurable except in contrived benchmarks).

For said contrived benchmarks, see: https://www.modernescpp.com/index.php/memory-and-performance-overhead-of-smart-pointer

### CODE REVIEW

**Comment by jonoomph** [comment]
LGTM!

**Comment by ferdnyc** [comment]
@jonoomph I decided to let Codacy shame me into fixing that initialization issue, and replace all of the redundant Frame constructors with delegating constructors.

**Comment by jonoomph** [comment]
This one is going to have some conflicts with my new clip-refactor-keyframes branch, yikes.

**Comment by jonoomph** [comment]
This might wait until after I merge  `clip-refactor-keyframes` branch

**Comment by jonoomph** [comment]
Okay, I'm going to bite the bullet, merge this, and then merge develop back into my `clip-refactor-keyframes` branch and resolve all the errors.

**Pull request merged**
