### PR TITLE
cmake: use GNUInstallDirs and fix documentation installation

### PR DESCRIPTION
**Pull request by alaviss**
This allows customizing various installation folders.

### CODE REVIEW

**Comment by jonoomph** [comment]
@alaviss Is this a duplicate of #? If not, can you please edit this PR and target the following branch instead of develop: https://github.com/OpenShot/libopenshot/tree/improve-cmake. Thanks!

**Comment by alaviss** [comment]
No, #159 depends on this PR. I simply merged this branch over there with a merge commit to declare dependency, but I don't think github supports that.

**Comment by alaviss** [comment]
@jonoomph 
> Is there some great benefit we get from switching to GNUInstallDirs? Or is the functionality the same as our current method? Thx

Functionally it's still the same. The different is that instead of hardcoding paths like `share/doc`, it's possible for packager to modify them. This is needed for systems that doesn't follow the typical *nix file system heirarchy.

The defaults of those variable should be the same as what they replace. You can consult CMake's [`GNUInstallDirs`](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html) reference for more information.

**Comment by jonoomph** [comment]
@alaviss Sorry this PR was not better handled. We have some new PRs (i.e. https://github.com/OpenShot/libopenshot/pull/253) that address these same issues... or most of them I believe. I'm going to go ahead and close this one. But feel free to submit a new one if you still have issues after our latest merges, and if you don't see a quick response from me, you can also contact me at jonathan@openshot.org anytime.

**Pull request closed without merging**
