### PR TITLE
Update Python install path detection

### PR DESCRIPTION
**Pull request by ferdnyc**
This changes the `PYTHON_MODULE_PATH` handling in two ways:

* Makes it a cache variable, so detection is only run once and
  only if it's not already set. This allows it to be overridden
  on the command line, e.g.
  `cmake -DPYTHON_MODULE_PATH:PATH=lib/python3.6/dist-packages`

* Uses the presence of the `pybuild` executable to sense for
  a Debian-derived system (only on UNIX AND NOT APPLE), and
  if found it falls back to the old `getsitepackages()[0]`
  path extraction method.

This works in my tests on Fedora and Ubuntu 18.10, hopefully older/Mintyer will prove the same. `pybuild` is part of dh-python, which synaptic reports as a dependency of `python3-dev` and `python3-all`, so here's hoping...

### CODE REVIEW

**Comment by ferdnyc** [comment]
Travis clearly detected `pybuild`, so that's a good sign:
`-- Will install Python module to: lib/python3.5/dist-packages`

**Comment by ferdnyc** [comment]
Speaking of... hey @jonoomph , I noticed Travis doesn't run the `make install` part of the build — maybe it should, to verify that the CMake tooling hasn't broken? It can always use a throwaway path like:
```console
$ make install DESTDIR=dist/
make install DESTDIR=dist/
[ 73%] Built target openshot
[ 75%] Built target openshot-example
[ 77%] Built target openshot-player
[ 78%] Built target pyopenshot_swig_compilation
[ 80%] Built target pyopenshot
[ 81%] Built target rbopenshot_swig_compilation
[ 83%] Built target rbopenshot
[100%] Built target openshot-test
Install the project...
-- Install configuration: ""
-- Installing: dist/usr/lib64/python3.7/site-packages/_openshot.so
-- Set runtime path of "dist//usr/lib64/python3.7/site-packages/_openshot.so" to ""
-- Installing: dist/usr/lib64/python3.7/site-packages/openshot.py
-- Up-to-date: dist/usr/lib64/ruby/vendor_ruby/openshot.so
-- Installing: dist/usr/lib/libopenshot.so.0.2.3
-- Installing: dist/usr/lib/libopenshot.so.17
-- Installing: dist/usr/lib/libopenshot.so
-- Installing: dist/usr/include/libopenshot
-- Installing: dist/usr/include/libopenshot/KeyFrame.h
-- Installing: dist/usr/include/libopenshot/Exceptions.h
-- Installing: dist/usr/include/libopenshot/WriterBase.h
-- Installing: dist/usr/include/libopenshot/Json.h
-- Installing: dist/usr/include/libopenshot/CacheBase.h
-- Installing: dist/usr/include/libopenshot/ImageWriter.h
-- Installing: dist/usr/include/libopenshot/Point.h
-- Installing: dist/usr/include/libopenshot/ReaderBase.h
-- Installing: dist/usr/include/libopenshot/effects
-- Installing: dist/usr/include/libopenshot/effects/Negate.h
-- Installing: dist/usr/include/libopenshot/effects/Blur.h
-- Installing: dist/usr/include/libopenshot/effects/Brightness.h
-- Installing: dist/usr/include/libopenshot/effects/Saturation.h
-- Installing: dist/usr/include/libopenshot/effects/Bars.h
-- Installing: dist/usr/include/libopenshot/effects/ChromaKey.h
-- Installing: dist/usr/include/libopenshot/effects/Crop.h
-- Installing: dist/usr/include/libopenshot/effects/Hue.h
-- Installing: dist/usr/include/libopenshot/effects/Mask.h
-- Installing: dist/usr/include/libopenshot/effects/Shift.h
-- Installing: dist/usr/include/libopenshot/effects/Deinterlace.h
-- Installing: dist/usr/include/libopenshot/effects/Wave.h
-- Installing: dist/usr/include/libopenshot/effects/Pixelate.h
-- Installing: dist/usr/include/libopenshot/effects/ColorShift.h
-- Installing: dist/usr/include/libopenshot/Frame.h
-- Installing: dist/usr/include/libopenshot/DecklinkOutput.h
-- Installing: dist/usr/include/libopenshot/AudioResampler.h
-- Installing: dist/usr/include/libopenshot/EffectBase.h
-- Installing: dist/usr/include/libopenshot/Clip.h
-- Installing: dist/usr/include/libopenshot/FrameMapper.h
-- Installing: dist/usr/include/libopenshot/Profiles.h
-- Installing: dist/usr/include/libopenshot/QtImageReader.h
-- Installing: dist/usr/include/libopenshot/Settings.h
-- Installing: dist/usr/include/libopenshot/RendererBase.h
-- Installing: dist/usr/include/libopenshot/FFmpegReader.h
-- Installing: dist/usr/include/libopenshot/EffectInfo.h
-- Installing: dist/usr/include/libopenshot/Tests.h
-- Installing: dist/usr/include/libopenshot/FFmpegUtilities.h
-- Installing: dist/usr/include/libopenshot/ZmqLogger.h
-- Installing: dist/usr/include/libopenshot/Enums.h
-- Installing: dist/usr/include/libopenshot/CacheDisk.h
-- Installing: dist/usr/include/libopenshot/Color.h
-- Installing: dist/usr/include/libopenshot/Version.h
-- Installing: dist/usr/include/libopenshot/DecklinkInput.h
-- Installing: dist/usr/include/libopenshot/ChannelLayouts.h
-- Installing: dist/usr/include/libopenshot/FFmpegWriter.h
-- Installing: dist/usr/include/libopenshot/Coordinate.h
-- Installing: dist/usr/include/libopenshot/PlayerBase.h
-- Installing: dist/usr/include/libopenshot/OpenShot.h
-- Installing: dist/usr/include/libopenshot/ClipBase.h
-- Installing: dist/usr/include/libopenshot/DecklinkWriter.h
-- Installing: dist/usr/include/libopenshot/ChunkWriter.h
-- Installing: dist/usr/include/libopenshot/Timeline.h
-- Installing: dist/usr/include/libopenshot/Qt
-- Installing: dist/usr/include/libopenshot/Qt/PlayerPrivate.h
-- Installing: dist/usr/include/libopenshot/Qt/VideoCacheThread.h
-- Installing: dist/usr/include/libopenshot/Qt/PlayerDemo.h
-- Installing: dist/usr/include/libopenshot/Qt/VideoRenderWidget.h
-- Installing: dist/usr/include/libopenshot/Qt/VideoPlaybackThread.h
-- Installing: dist/usr/include/libopenshot/Qt/AudioPlaybackThread.h
-- Installing: dist/usr/include/libopenshot/Qt/VideoRenderer.h
-- Installing: dist/usr/include/libopenshot/Effects.h
-- Installing: dist/usr/include/libopenshot/OpenMPUtilities.h
-- Installing: dist/usr/include/libopenshot/DummyReader.h
-- Installing: dist/usr/include/libopenshot/CacheMemory.h
-- Installing: dist/usr/include/libopenshot/TextReader.h
-- Installing: dist/usr/include/libopenshot/Fraction.h
-- Installing: dist/usr/include/libopenshot/AudioReaderSource.h
-- Installing: dist/usr/include/libopenshot/ChunkReader.h
-- Installing: dist/usr/include/libopenshot/DecklinkReader.h
-- Installing: dist/usr/include/libopenshot/CrashHandler.h
-- Installing: dist/usr/include/libopenshot/AudioBufferSource.h
-- Installing: dist/usr/include/libopenshot/ImageReader.h
-- Installing: dist/usr/include/libopenshot/QtPlayer.h
```

**Comment by jonoomph** [comment]
Thanks @ferdnyc! This is interesting. I have no complaints. However, I'll circle back around to this PR soon, once I merge in the `hardware-support` branch... since we also made some changes to the Python install path.

**Comment by jonoomph** [comment]
Fixing merge conflict...

**Comment by jonoomph** [comment]
@ferdnyc Thanks for this! Fingers crossed it works across all the platforms. I'll be watching the GitLab build servers and PPA build servers. I'll keep you posted.

**Pull request merged**
