### PR TITLE
Upgrade Doxygen documentation formatting/content

### PR DESCRIPTION
**Pull request by ferdnyc**
**EDIT:** Retitled because this PR has become sort of a catch-all of upgrades to the documentation. See later comments for other changes I threw in "while I was touching the Doxygen stuff"...

Recent versions of Doxygen emit a ton of warnings when `make doc` is run. This fixes the two biggest issues:

1. The Python sources were being processed, including the SWIG output. To prevent this, `*.py` is added to the excluded files in `Doxygen.in`.

2. Doxygen now complains when `@section` is abused the way it is in the libopenshot documentation headers. (The [documentation indicates](http://www.doxygen.nl/manual/commands.html#cmdsection) that section is a page-level command, not meant to be used in other contexts. And section names need to be unique, as they can be referenced with `@ref`. So, `@section LICENSE` multiple times throughout the source is a no-no.)

This PR actually solves this by _**removing**_ the license statement from the documentation block, and moving it into a regular comment block which Doxygen ignores. The license statement (which was previously included in the documentation of every file) is instead replaced with a reference to the license section on the `@mainpage`, as defined in `include/OpenShot.h`. So `include/Enums.h` will have this header:
```c++
/**
 * @file
 * @brief Header file for TextReader class
 * @author Jonathan Thomas <jonathan@openshot.org>
 *
 * @ref License
 */

/* LICENSE
 *
 * Copyright (c) 2008-2014 OpenShot Studios, LLC
 * <http://www.openshotstudios.com/>. This file is part of
 * OpenShot Library (libopenshot), an open-source project dedicated to
 * delivering high quality video editing and animation solutions to the
 * world. For more information visit <http://www.openshot.org/>.
 *
[...]
```

Resulting in this documentation page:
> image

The "License" link leads to the bottom of the main page:
> image

### CODE REVIEW

**Comment by jeffski** [comment]
The copyright date is 2014, should that be updated? Also it would be great if https://openshot.org/files/libopenshot/ could be updated with the latest version.  Probably not a huge issue but I do refer to those online docs quite regularly.

**Comment by ferdnyc** [comment]
> The copyright date is 2014, should that be updated? 

`¯\_(ツ)_/¯` I mean, the copyrights are all over the place. TBH I've never understood the logic of "year-range" copyright statements, I'm not sure I've ever seen one that actually goes up to the current year. It's just a guaranteed way to make your info seem even more out of date than just "Copyright 2008".

(Actually, the _comments in general_ are kind of all over the place. That wasn't a typo on my part, above (as I initially thought): `Enums.h` really does claim to be the "Header file for TextReader class".)

_But_, I guess if I'm touching every file anyway, I could be persuaded to update it to "2008 - 2019". Then it'll be current for a whole 6 months! :+1: 

> Also it would be great if https://openshot.org/files/libopenshot/ could be updated with the latest version. Probably not a huge issue but I do refer to those online docs quite regularly.

@jonoomph is the only one who can do that, AFAIK. I think it'd be great if they were regenerated every build, personally. It'll keep people honest! (Meaning: Actually updating documentation.)

No reason the same builders that are building binary packages and auto-posting them as Daily Builds can do a `make doc`, while they're in there, and upload the results of that process to the server as well.

**Comment by jeffski** [comment]
I would have thought that this would cover all copyright and license requirements: https://github.com/OpenShot/libopenshot/blob/develop/COPYING so anywhere else in the codebase probably isn't needed and will save having to ever update files and dates in the future. I'm not a lawyer though :)

Agree, update the docs during build would be great.

**Comment by ferdnyc** [comment]
> I would have thought that this would cover all copyright and license requirements: https://github.com/OpenShot/libopenshot/blob/develop/COPYING so anywhere else in the codebase probably isn't needed and will save having to ever update files and dates in the future. I'm not a lawyer though :)

The argument for placing a license statement in each source file is that, since it's open source, you never know when one might make its way into some other project, separate from the rest of the code. Which would be perfectly file, according to the license, but it still needs to be tracked by packagers and the like. So, there's some sense in that.

...I don't think it needs to be _dated_ in every file, though.

**Comment by chad3814** [comment]
it wouldn't be super-hard to set up a webhook for when code was pushed to develop that checked out that code, built the docs and pushed that to a gh-pages branch or a OpenShot.github.io repo, then the docs would be up-to-date there...

**Comment by ferdnyc** [comment]
I've added commits that will link the new MarkDown files in `doc` into the API documentation as well, so there will still be install guides provided even in the absence of `doc/InstallGuide.pdf`. (I had to make a bunch of minor formatting changes, as a result, since Doxygen's MarkDown parser is pickier than GitHub's.)

And I just pushed a commit to switch on a cool feature that FFmpeg use in their API docs: Referenced-by links. So now, when you're reading about e.g. `openshot::ReaderBase::Open()`, in addition to seeing the list of all the places where it's implemented (the "Implemented by..." list), you can also see all of the _other_ places in the code where it gets called ("Referenced by..."):

image

**Comment by ferdnyc** [comment]
More commits added, fixing up some bugs in `UseDoxygen.cmake` that were preventing the use of `dot` for graphs, and then enabling it. Using `dot` increases the documentation generation time — on my system it went from basically-instantaneous to a little over 20 seconds — but in return we get _much_ cooler graphs, such as this collaboration diagram from `openshot::Clip`:

image

I also set the graphs to be generated as SVG, and turned on the `INTERACTIVE_SVG` option. That makes the graphs zoomable and pannable, which is necessary because some of the include graphs go all crazy-spaghetti, and having a zoomable bowl of pasta that fits on the screen is better than it being a **gigantic** PNG file that _doesn't_ fit on the screen and makes you scroll like crazy.

If the dot executable isn't found when generating the docs, it won't be used and the less-exciting graphs will be generated instead.

There are actually even more cool graphs that can be enabled — both caller and call graphs for functions — but those are of limited use on _every_ function, and blow out the generation time like you wouldn't believe. The Doxygen docs suggest only enabling them for _certain_ functions (which can be done by including a `@callgraph` or `@callergraph` command in its documentation comment), probably the sensible solution though it means somebody has to go through and make those decisions. If nothing else, they should be _disabled_ (`@hidecallgraph`/`@hidecallergraph`) for all the JSON-related functions, as those are over-referenced to the point of incomprehensibility.

**Comment by ferdnyc** [comment]
Crazy-spaghetti example, the include graph for `OpenShot.h`:
image

**Comment by jonoomph** [comment]
@ferdnyc @chad3814 I love the idea of updating docs during our build server hooks. I'll take a look at that (should be pretty easy... in theory). Thanks for the updated docs.

**Comment by jonoomph** [comment]
What version of Doxygen is needed for these changes? I'm seeing the following output on my "older" build server, Ubuntu 14.04 (which is still recommended by AppImage folks).

```
$ make doc
Scanning dependencies of target doxygen
[100%] Writing documentation to /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/doc...
Warning: ignoring unsupported tag `ALLOW_UNICODE_NAMES    =' at line 79, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `OUTPUT_TEXT_DIRECTION  =' at line 102, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `OPTIMIZE_OUTPUT_SLICE  =' at line 286, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `TOC_INCLUDE_HEADINGS   =' at line 325, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `GROUP_NESTED_COMPOUNDS =' at line 382, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `HIDE_COMPOUND_REFERENCE=' at line 553, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `WARN_AS_ERROR          =' at line 778, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `HTML_DYNAMIC_MENUS     =' at line 1213, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `LATEX_MAKEINDEX_CMD    =' at line 1677, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `LATEX_EXTRA_STYLESHEET =' at line 1744, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `LATEX_TIMESTAMP        =' at line 1811, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `LATEX_EMOJI_DIRECTORY  =' at line 1819, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `RTF_SOURCE_CODE        =' at line 1885, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `MAN_SUBDIR             =' at line 1920, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `XML_NS_MEMB_FILE_SCOPE =' at line 1963, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `DOCBOOK_PROGRAMLISTING =' at line 1990, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `PLANTUML_JAR_PATH      =' at line 2419, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `PLANTUML_CFG_FILE      =' at line 2424, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
Warning: ignoring unsupported tag `PLANTUML_INCLUDE_PATH  =' at line 2429, file /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/Doxyfile
[100%] Built target doxygen
Scanning dependencies of target doc
[100%] Built target doc
```

**Comment by jonoomph** [comment]
I'm going try building doxygen from source, to get us a more recent version on our builder (this is so I can auto-update the docs on our website)

**Comment by jonoomph** [comment]
Yup, I was able to update Doxygen to a more recent version, and no more warnings. Everything seems to look correct, with respects to the generated HTML files! Nice!!! I've added the auto-updating to a new PR (https://github.com/OpenShot/libopenshot/pull/258).

It took a bit more time than I thought to hook this up. I've opted to hide the specifics of how this works, since it deals with SSH keys and internal workings of the OpenShot website. I've locked it down pretty well though, and it only allows a single command between the runner and the web server, and is locked to a specific folder (i.e. the libopenshot files).

**Pull request merged**
