### PR TITLE
Fix issues in Blur.cpp by copying blur_<chan> values back to <chan> so horizont…

### PR DESCRIPTION
**Pull request by N3WWN**
…al *and* vertical blurs can be applied in one effect and blur accumulates with increased iterations

Resolves issues https://github.com/OpenShot/openshot-qt/issues/1554 and https://github.com/OpenShot/openshot-qt/issues/1575

### CODE REVIEW

**Comment by peanutbutterandcrackers** [comment]
Bravo, Mr. Alloway! You're the best!

**Comment by N3WWN** [comment]
> Bravo, Mr. Alloway! You're the best!

Thank you, Sir @peanutbutterandcrackers !  But you used my real name and now I'll never get any rest with the line of companies beating a path to my door every day! 🤣

**Comment by peanutbutterandcrackers** [comment]
Haha. I hope some company will hire you to make contributions to Open Source Projects so that they can boost their good will. That would be awesome. But then again, you're already developing Cent OS. :D

**Comment by N3WWN** [comment]
@peanutbutterandcrackers - Oddly enough, you just described $dayjob to a T!  I mean, it's uncanny how accurate your description is!

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - Wow! You're living the GNU-merican dream! :) :+1:

**Comment by jonoomph** [comment]
Nice!!!

**Pull request merged**
