### PR TITLE
Revert "3 New OpenCV Effects (Tracker, Stabilization, and Object Detection)"

### PR DESCRIPTION
**Pull request by jonoomph**
Reverts OpenShot/libopenshot#585

I'm seeing lots of failures on our build servers all of a sudden. Need to investigate. @BrennoCaldato

### CODE REVIEW

**Comment by jonoomph** [comment]
```
[ 66%] Building CXX object src/CMakeFiles/openshot.dir/effects/Stabilizer.cpp.obj
cd /C/Users/Administrator/builds/7546b651/0/OpenShot/libopenshot/build/src && /C/msys64/mingw64/bin/g++.exe  -DHAVE_ISFINITE=1 -DIGNORE_JUCE_HYPOT=1 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DUSE_OPENCV=1 -DUSE_RESVG=1 -Dopenshot_EXPORTS -I/C/Users/Administrator/builds/7546b651/0/OpenShot/libopenshot/build/src/openshot_autogen/include -I/C/Users/Administrator/builds/7546b651/0/OpenShot/libopenshot/src -I/C/Users/Administrator/builds/7546b651/0/OpenShot/libopenshot/build/src -isystem /C/Users/Administrator/builds/7546b651/0/OpenShot/libopenshot/build/install-x64/include/libopenshot-audio -isystem /C/msys64/mingw64/include/QtCore -isystem /C/msys64/mingw64/share/qt5/mkspecs/win32-g++ -isystem /C/msys64/mingw64/include/QtGui -isystem /C/msys64/mingw64/include/QtWidgets -isystem /C/msys64/usr/include/resvg -isystem /C/msys64/usr/local/include  -O3 -DNDEBUG   -include cmath -fopenmp -std=c++11 -o CMakeFiles/openshot.dir/effects/Stabilizer.cpp.obj -c /C/Users/Administrator/builds/7546b651/0/OpenShot/libopenshot/src/effects/Stabilizer.cpp
C:/Users/Administrator/builds/7546b651/0/OpenShot/libopenshot/src/effects/Stabilizer.cpp: In member function 'virtual void openshot::Stabilizer::SetJson(std::string)':
C:/Users/Administrator/builds/7546b651/0/OpenShot/libopenshot/src/effects/Stabilizer.cpp:204:9: error: 'InvalidJSON' was not declared in this scope
  204 |   throw InvalidJSON("JSON is invalid (missing keys or invalid data types)");
      |         ^~~~~~~~~~~
mingw32-make[2]: *** [src/CMakeFiles/openshot.dir/build.make:911: src/CMakeFiles/openshot.dir/effects/Stabilizer.cpp.obj] Error 1
mingw32-make[2]: Leaving directory 'C:/Users/Administrator/builds/7546b651/0/OpenShot/libopenshot/build'
mingw32-make[1]: *** [CMakeFiles/Makefile2:194: src/CMakeFiles/openshot.dir/all] Error 2
mingw32-make[1]: Leaving directory 'C:/Users/Administrator/builds/7546b651/0/OpenShot/libopenshot/build'
mingw32-make: *** [Makefile:155: all] Error 2
```

**Comment by jonoomph** [comment]
I think it might be related to a bad merge with `develop`, and the exclusion of "Exceptions.h" in "OpenShot.h" header

**Comment by jonoomph** [comment]
@ferdnyc @BrennoCaldato Any ideas on a fix for develop? Or do you think I should revert this entire thing and we can fix it offline? I have a feeling something related to "Exceptions.h" was merged in from develop incorrectly.

**Comment by ferdnyc** [comment]
@jonoomph Sounds like my fault. Sorry, been busy this week, we've been having plumbing crises. But let me take a quick look now.

**Comment by ferdnyc** [comment]
It looks like Stabilizer.cpp just needs a `#include "Exceptions.h"` -- it was probably picking it up from some random one of the other headers, previously. (That's the sort of header creep I've been trying to tame, by moving includes into the source files when possible.

**Comment by ferdnyc** [comment]
Fixing in #625.

**Comment by ferdnyc** [comment]
@jonoomph @BrennoCaldato 

Anybody know the Ubuntu apt packages that need to be installed for OpenCV and Protocol Buffers support? My VM is being a pain about starting up and looking it up on the web sounds like a chore.

**Comment by jonoomph** [comment]
Here are the basic instructions I've been using:
```
sudo apt-get install build-essential

sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev

sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev

sudo apt -y install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

sudo apt -y install libgtk2.0-dev libtbb-dev qt5-default

sudo apt-get install ffmpeg libeigen3-dev

mkdir Libraries
cd Libraries/

git clone https://github.com/opencv/opencv
cd opencv/
git checkout '4.3.0'
cd ..

git clone https://github.com/opencv/opencv_contrib
cd opencv_contrib/
git checkout '4.3.0'
cd ..

cd opencv
mkdir build
cd build/

cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D WITH_TBB=OFF -D WITH_V4L=ON -D OPENCV_PYTHON3_INSTALL_PATH=$cwd/OpenCV-$cvVersion-py3/lib/python3.5/site-packages -D WITH_QT=ON -D WITH_CUDA=ON -D WITH_OPENGL=ON -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules -D OPENCV_GENERATE_PKGCONFIG=ON -D BUILD_EXAMPLES=ON ..

make -j9
sudo make install
```

**Comment by jonoomph** [comment]
I'm not sure what repo versions and apt packages are required though

**Comment by ferdnyc** [comment]
I believe I've got it. The answer, from an `apt` perspective, appears to be:

`libopencv-dev libprotobuf-dev protobuf-compiler`

(Leave out that last one, you'll get _very_ strange errors because instead of being replaced with the path to the `protoc` executable, the `protobuf::protoc` target ends up in the Makefile as a dependency. Which breaks it completely, `::` not being valid unescaped path characters in Make.)

Installing individual OpenCV library components (e.g. `libopencv-core-dev`, etc. is a nice idea, to avoid installation bloat, and that's how I started. But none of them install the CMake configs needed to properly configure the targets. So I have to figure out which package those files live in, to make it more focused.

**Comment by ferdnyc** [comment]
@jonoomph @BrennoCaldato 

So, builds are fixed, I think this can be closed unmerged no? Doesn't seem necessary.

**Comment by jonoomph** [comment]
@ferdnyc Yup, closing now. Thanks so much! And good notes on the packages above!

**Pull request closed without merging**
