### PR TITLE
Gitlab-CI: Update Windows builder configs, OpenShotAudio linking; enable Windows unit tests

### PR DESCRIPTION
**Pull request by ferdnyc**
This PR (which has OpenShot/libopenshot-audio#118 and OpenShot/libopenshot-audio#119 as prerequisites) similarly updates the Windows project builder configs to match their enhanced MinGW32/64 environments, but also makes some changes of general note:

1. The `FindOpenShotAudio.cmake` module is deleted from `cmake/Modules/`. CMake will now use the `EXPORTED` CMake configuration produced (pending the merge of OpenShot/libopenshot-audio#118) when building and installing the "OpenShotAudio" project — aka `libopenshot-audio` —  to confgure that dependency, making the Find module unnecessary.

    If `OpenShotAudio` is built and installed in a _system default_ location like `/usr/` or `C:\msys64\mingw32\`, one where CMake is configured to look for package configs by default, then the `<prefix>/share/cmake/OpenShotAudio/OpenShotAudioConfig.cmake` files will be picked up _automatically_ when configuring the libopenshot build ­— nothing needs to be done.

    If the `OpenShotAudio` build has been installed in a non-standard location (say, `/opt/OpenShotAudio`, then any CMake >= 3.12 can be directed to the configuration by setting the `OpenShotAudio_ROOT` variable to that prefix path. e.g.:
    ```sh
    cmake -B build -S . -DOpenShotAudio_ROOT=/opt/OpenShotAudio ...
    ```
    CMake will discover the `/opt/OpenShotAudio/share/cmake/OpenShotAudio/` directory created by the OpenShotAudio install, and configure the build in accordance with its contents.

    `OpenShotAudio_ROOT` can also be pointed at a _build_ directory to pick up the dependency there, without installing the project. However, this is likely to cause problems on Linux once libopenshot is installed, unless **at _that_ time** (if not before) `libopenshot-audio` is also installed to the same (system) library path. The current build configs conform to CMake's default Linux convention of disabling all `RPATH`s on installed binaries and executables.

1. The OpenShotAudio main header file will have a new name as of OpenShot/libopenshot-audio#118, so all `#includes` in the libopenshot code have been replaced:
    ```c++
    // Old form
    #include "JuceHeader.h"
    // New form
    #include <OpenShotAudio.h>
    ````
    The header is _also_ still installed under the old name, for backwards-compatibility, but this should be considered deprecated and subject to future removal. A compile-time warning may eventually be emitted when the `JuceHeader.h` file is included, to raise awareness of this change.
    
    Only the header file name has changed; audio classes defined in OpenShotAudio are still under the `juce::` namespace, same as before.

1. Catch2 unit tests are now runnable on any Windows system that has the `mingw-w64-*-catch` package(s) installed in MSYS2. (Or any system where Catch2 is manually installed and visible to CMake.)

    The only other requirement is that every DLL dependency _other than_ `libopenshot-audio.dll` must be located on the `$PATH` and accessible to the unit test `openshot-*-test.exe` files when they're run during the build. The build script will copy the necessary libopenshot and libopenshot-audio DLLs into the unit test space so they can be found, it's only external dependencies that need to be accessible via `$PATH`.

1. Minor, but the `<build>/examples/openshot-html-test` program compiled from `examples/ExampleHtml.cpp` is renamed to `<build>/examples/openshot-html-example`. All of the new unit test executables are named `<build>/tests/openshot-<class>-test`, so the old name was destined to cause confusion.

### CODE REVIEW

**Comment by ferdnyc** [comment]
(Again, this is expected to fail to build until OpenShot/libopenshot-audio#118 is merged, so the failures serve as a handy reminder that the other PR needs to go in first.)

**Comment by ferdnyc** [comment]
Well, OpenShot/libopenshot-audio#118 is merged, but the PPA manifest needs to have the `/usr/share/cmake/OpenShotAudio/*.cmake` files added to it so they'll be packaged. @jonoomph , I submitted a merge request @ launchpad for that, if you have a moment to review it? https://code.launchpad.net/~ferdnyc/openshot-packaging/+git/openshot-packaging-1/+merge/401348

**Comment by jonoomph** [comment]
@ferdnyc LaunchPad merge request approved! Thx

**Comment by ferdnyc** [comment]
@jonoomph Thanks! I triggered a new build of the libopenshot-audio DEBs, and it looks from the build log like the CMake configs are indeed packaged, so fingers crossed that this will now build successfully in CI and can be merged.

**Comment by ferdnyc** [comment]
UGGGGGGGGH.

```text
CMake Error at /usr/share/cmake/OpenShotAudio/OpenShotAudioTargets.cmake:84 (message):
-- Configuring incomplete, errors occurred!
See also "/home/runner/work/libopenshot/libopenshot/build/CMakeFiles/CMakeOutput.log".
  The imported target "OpenShot::openshot-audio-demo" references the file

     "/usr/bin/openshot-audio-demo"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/share/cmake/OpenShotAudio/OpenShotAudioTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/share/cmake/OpenShotAudio/OpenShotAudioConfig.cmake:72 (include)
  src/CMakeLists.txt:178 (find_package)


Error: Process completed with exit code 1.
```

(I just merged OpenShot/libopenshot-audio#121 to remove the demo binary from the EXPORTED configuration.)

**Comment by jonoomph** [comment]
Nice job!

**Pull request merged**
