### PR TITLE
Apply time keyframes to the correct clip frame number

### PR DESCRIPTION
**Pull request by JacksonRG**
# Issue
1) Drag a video file onto the timeline
2) Reverse the video (`Right click` > `Time` > `Normal` > `Backwards 1x`)
3) At the beginning of the clip drag the preview to the left
4) At the end of the clip drag the preview to the right
5) Preview, and see the clip moving in the wrong direction
(Also test a 2x speed clip. The clip will only get half way across the screen)

# Test
Repeat the issue above, and observe the preview moving in the correct direction

### CODE REVIEW

**Comment by jonoomph** [comment]
@JacksonRG It seems like the "real" issue here is that we replace the "frame" object in the `apply_keyframes()` method, and thus the `frame->number` is replaced with the time mapped frame number. Perhaps the `apply_keyframes` method should never replace the `frame->number`, and thus, this PR gets a whole lot simpler, and we don't need the `unmapped_frame` variable (which is the wrong type by the way - should be int64_t).  How does that sound?

**Comment by JacksonRG** [comment]
That makes sense. (I think I went unsigned because it shouldn't be able to be negative.) (though maybe that's bad flawed logic if the timing data is real weird)

**Review by jonoomph — APPROVED** [review]
LGTM

**Comment by jonoomph** [comment]
@JacksonRG We should probably add a unit test for this one, since we've already seen a regression on this feature. For example, adding both a `scale_x` and `time` keyframe, and verifying keyframe values... What do you think?

**Comment by JacksonRG** [comment]
Just rebased to re-run the checks. Merging pending success

**Pull request merged**
