### PR TITLE
WIP: Use CTest to run tests

### PR DESCRIPTION
**Pull request by ferdnyc**
This PR moves to running our tests with the CTest component of CMake, integrating them better into the CMake environment.

To help facilitate this, the 14 different test source files are compiled into 14 different executables, instead of just a single `openshot-test` program which runs all of them. They can then be run as a unit using `make test`, or selectively with `ctest -R $include_regexp` or `ctest -E $exclude_regexp`

```console
$ make test
Running tests...
Test project /home/ferd/rpmbuild/REPOS/libopenshot/build_ctest
      Start  1: Cache
 1/14 Test  #1: Cache ............................   Passed    0.36 sec
      Start  2: Clip
 2/14 Test  #2: Clip .............................   Passed    0.68 sec
      Start  3: Color
 3/14 Test  #3: Color ............................   Passed    0.08 sec
      Start  4: Coordinate
 4/14 Test  #4: Coordinate .......................   Passed    0.07 sec
      Start  5: ReaderBase
 5/14 Test  #5: ReaderBase .......................   Passed    0.07 sec
      Start  6: ImageWriter
 6/14 Test  #6: ImageWriter ......................   Passed    2.91 sec
      Start  7: FFmpegReader
 7/14 Test  #7: FFmpegReader .....................   Passed    2.08 sec
      Start  8: FFmpegWriter
 8/14 Test  #8: FFmpegWriter .....................   Passed    1.33 sec
      Start  9: Fraction
 9/14 Test  #9: Fraction .........................   Passed    0.07 sec
      Start 10: FrameMapper
10/14 Test #10: FrameMapper ......................   Passed    0.65 sec
      Start 11: KeyFrame
11/14 Test #11: KeyFrame .........................   Passed    0.39 sec
      Start 12: Point
12/14 Test #12: Point ............................   Passed    0.07 sec
      Start 13: Settings
13/14 Test #13: Settings .........................   Passed    0.07 sec
      Start 14: Timeline
14/14 Test #14: Timeline .........................   Passed    0.84 sec

100% tests passed, 0 tests failed out of 14

Total Test time (real) =   9.67 sec

$ ctest -R Writer
Test project /home/ferd/rpmbuild/REPOS/libopenshot/build_ctest
    Start 6: ImageWriter
1/2 Test #6: ImageWriter ......................   Passed    2.90 sec
    Start 8: FFmpegWriter
2/2 Test #8: FFmpegWriter .....................   Passed    1.33 sec

100% tests passed, 0 tests failed out of 2

Total Test time (real) =   4.23 sec

$ # After I modified Color_Tests.cpp so that one of the tests fails:
$ make; make test
[rebuilding]
Running tests...
Test project /home/ferd/rpmbuild/REPOS/libopenshot/build_ctest
      Start  1: Cache
 1/14 Test  #1: Cache ............................   Passed    0.36 sec
      Start  2: Clip
 2/14 Test  #2: Clip .............................   Passed    0.67 sec
      Start  3: Color
 3/14 Test  #3: Color ............................***Failed    0.07 sec
      Start  4: Coordinate
 4/14 Test  #4: Coordinate .......................   Passed    0.07 sec
      Start  5: ReaderBase
 5/14 Test  #5: ReaderBase .......................   Passed    0.07 sec
      Start  6: ImageWriter
 6/14 Test  #6: ImageWriter ......................   Passed    2.90 sec
      Start  7: FFmpegReader
 7/14 Test  #7: FFmpegReader .....................   Passed    2.08 sec
      Start  8: FFmpegWriter
 8/14 Test  #8: FFmpegWriter .....................   Passed    1.33 sec
      Start  9: Fraction
 9/14 Test  #9: Fraction .........................   Passed    0.07 sec
      Start 10: FrameMapper
10/14 Test #10: FrameMapper ......................   Passed    0.62 sec
      Start 11: KeyFrame
11/14 Test #11: KeyFrame .........................   Passed    0.38 sec
      Start 12: Point
12/14 Test #12: Point ............................   Passed    0.07 sec
      Start 13: Settings
13/14 Test #13: Settings .........................   Passed    0.07 sec
      Start 14: Timeline
14/14 Test #14: Timeline .........................   Passed    0.84 sec

93% tests passed, 1 tests failed out of 14

Total Test time (real) =   9.61 sec

The following tests FAILED:
	  3 - Color (Failed)
Errors while running CTest
make: *** [Makefile:152: test] Error 8
```

A legacy `os_test` target is still created, which runs all 14 of the test executables (outside of CTest), though I may change that to just execute the `ctest` command instead.

This is still a WIP for two reasons, one _incredibly_ stupid, one worth further consideration:

1. While `make test` after building the project will run the tests, `make test` _without_ the project being built **WON'T** first build the project, it'll simply fail on the missing test executables. 

    ```
    $ make clean; make test
    [lots of file-search spew]
    0% tests passed, 14 tests failed out of 14
    
    Total Test time (real) =   0.03 sec
    
    The following tests FAILED:
    	  1 - Cache (Not Run)
    	  2 - Clip (Not Run)
    	  3 - Color (Not Run)
    	  4 - Coordinate (Not Run)
    	  5 - ReaderBase (Not Run)
    	  6 - ImageWriter (Not Run)
    	  7 - FFmpegReader (Not Run)
    	  8 - FFmpegWriter (Not Run)
    	  9 - Fraction (Not Run)
    	 10 - FrameMapper (Not Run)
    	 11 - KeyFrame (Not Run)
    	 12 - Point (Not Run)
    	 13 - Settings (Not Run)
    	 14 - Timeline (Not Run)
    Errors while running CTest
    make: *** [Makefile:152: test] Error 8
    ```

    That is colossally stupid, but [apparently by design](https://gitlab.kitware.com/cmake/community/wikis/doc/ctest/Testing-With-CTest) ("Once you have built the project..."), and I haven't found a clean way to fix it yet.

2. While the individual test executables give us individual results at a high-level, we still miss the granularity of UnitTest++'s per-source output. `make os_test` will show the "Success: N tests passed." message from each executable, but `make test` / `ctest` suppresses output by default and only shows pass/fail status.

    The solution to this may be to break the individual `tests/Thing_Tests.cpp` files up into directories of `tests/Thing/Subthing.cpp` files, one per test at the most granular level, instead of having all of the tests for a Thing be in one source file. I have to play with it more.

    1. Oh, and as a bonus issue, because the `os_test` target now runs 14 different executables, a failure in any one of them causes it to exit. So, `make os_test` will abort after the Color test failure, in my failure example above, without running the rest of the tests. (CTest doesn't have that limitation, though.)

### CODE REVIEW

**Comment by ferdnyc** [comment]
> 1. While `make test` after building the project will run the tests, `make test` _without_ the project being built **WON'T** first build the project, it'll simply fail on the missing test executables.

I'm not the only one who [feels that's a bug](https://stackoverflow.com/questions/733475/cmake-ctest-make-test-doesnt-build-tests), but there are some possible solutions in the answers there.

**Comment by musteresel** [comment]
Regarding the issue with `make test` not building the required executables: I've found ([here](https://musteresel.github.io/posts/2019/10/golden-tests-with-cmake.html) if anyone's interested) the approach using fixtures to work quite good and reliably.

Using fixtures here would mean to add the following to the loop body:

~~~cmake
add_test(${testname}-build
  "${CMAKE_COMMAND}"
  --build "${CMAKE_BINARY_DIR}"
  --config $<CONFIG>
  --target openshot-${testname}-test
  )
set_tests_properties(${testname}-build
  PROPERTIES FIXTURES_SETUP ${testname}-fixture)
set_tests_properties(${testname}
  PROPRETIES FIXTURES_REQUIRED ${testname}-fixture)
~~~

**Comment by ferdnyc** [comment]
@musteresel Hmmm... that could indeed be the missing link! It's got more potential than any other solution I've seen so far, at least. Thanks!

The whole FIXTURES concept was [introduced in CMake 3.7](https://cmake.org/cmake/help/v3.7/release/3.7.html), which does mean we'll either have to find an alternative solution for earlier CMakes, or just disclaim that the tests only work correctly in CMake 3.7+.

(Frustratingly, 3.7+ **doesn't** cover all of our target versions, even internally. Stinkin' MacOS builder running CMake 3.2! And even the Linux builder is running 3.5 IIRC. *\sigh\*)

**Comment by ferdnyc** [comment]
Closing this, as it will happen as part of the new Catch2 unit tests.

**Pull request closed without merging**
