### PR TITLE
Release of libopenshot 0.2.4 (SO 18)

### PR DESCRIPTION
**Pull request by jonoomph**
This PR represents the release branch for **libopenshot**, version 0.2.4 (SO 18), and will be used during the release testing. Feel free to comment, or send PR's for this release branch.

Related PR's:
 * libopenshot-audio release: https://github.com/OpenShot/libopenshot-audio/pull/80
 * openshot-qt release: https://github.com/OpenShot/openshot-qt/pull/3161

### CODE REVIEW

**Comment by jonoomph** [comment]
Oh, updating the CMakeLists.txt required version of libopenshot-audio is triggering a Travis failure. Hmmm

**Comment by ferdnyc** [comment]
@jonoomph 

So bump the `develop` version. That should've been done already, no? `develop` should always be ahead of any release branch, immediately after branching it should be updated to `$nextrelease-dev1`.

**Comment by ferdnyc** [comment]
(Er, where `$nextrelease` is the release being prepared in the release branch, not the one _after_ that.)

**Comment by ferdnyc** [comment]
I'll create PRs for the develop branches now.

**Comment by ferdnyc** [comment]
OpenShot/libopenshot#408, OpenShot/libopenshot-audio#81

**Comment by ferdnyc** [comment]
@jonoomph OK, 0b4885b pushed here, and also sitting on branch `resvg-image-format` to get an AppImage test-build. (I created a branch with the same name at OpenShot/openshot-qt as well, so it'll build through.)

**Comment by ferdnyc** [comment]
@jonoomph 

Oh, duh, of course you'll need to update resvg on all of the GitLab builders manually, to get the alpha-gradient fix. (The image format fix will work with the older version, presumably.)

After I `git pull`ed from @RazrFalcon's repo, I also had a to do a `rustup update` to the most recent rust toolchain, since the new code is using features that are marked experimental if the compiler's out of date, so it'll refuse to build.

But once that was sorted, it was just
```sh
cd resvg
git pull
cargo build --release --features="qt-backend"
cd capi
cargo build --release --features="qt-backend"
```

Then `cd ..`, and the headers are in `capi/include`, the library is `target/release/libresvg.so`.

**Comment by jonoomph** [comment]
Yup, Linux builder is updated. Working on Windows builders now... but they are much more difficult to upgrade rustc. Hoping for a simpler solution than installing experimental versions of rust for both 32-bit and 64-bit MSYS2 environments.

**Comment by ferdnyc** [comment]
That reminds me that I'd wanted to ask if @RazrFalcon has seen [cargo-c](https://dev.to/luzero/building-crates-so-they-look-like-c-abi-libraries-1ibn), for building & installing rust libraries as first-class `pkg-config` citizens.

**Comment by ferdnyc** [comment]
@jonoomph 
> Yup, Linux builder is updated. Working on Windows builders now... but they are much more difficult to upgrade rustc. Hoping for a simpler solution than installing experimental versions of rust for both 32-bit and 64-bit MSYS2 environments.

Any chance the sudden rash of builder failures is related to this? Hopefully it's not anything I did...

**Comment by jonoomph** [comment]
@ferdnyc Looks like the Windows builders are trying to link `RESVG::resvg-NOTFOUND`. That is causing the crash.

**Comment by jonoomph** [comment]
Also, Linux AppImages are breaking with some resvg linking error, but that could be a cache issue, where the libopenshot dlls are linked against the old one, and the openshot-qt package includes the new one... or something like that.

**Comment by ferdnyc** [comment]
@jonoomph That was an issue I hit with the new `IMPORTED` target, due to the fact that `libresvg.so` has no `SONAME`. I thought I'd pushed the commit to this branch that fixes it, but I don't see it. I'll add it now.

**Comment by ferdnyc** [comment]
The `NOTFOUND` issue, I know what that is, I remember hitting it with `ZeroMQ` as well. It's because of a Windows weirdness in how `.DLL` libs are discovered and linked. I should be able to fix it for resvg the same way.

**Comment by ferdnyc** [comment]
Huh, now suddenly 22793e2 _is_ here. That **should** fix the library linking in the AppImage. At least it did on my local system, but I'll check the logs to see if it did the right things.

But, as you say, could be that `openshot-qt` needs to regenerate — would it still build new AppImages if the Linux builder succeeded, but the Windows builders failed? Or would the Windows failures abort the entire pipeline?

**Comment by ferdnyc** [comment]
Yeah, in this run: http://gitlab.openshot.org/OpenShot/libopenshot/-/jobs/15054 resvg was linked with `-lrsvg` on the command line, instead of the full path. That should fix the dependency linking for the AppImage.

**Comment by ferdnyc** [comment]
@jonoomph  Did you cancel the most recent Travis run? It all succeeded except the Clang job, that got canceled before it could complete. But I don't see any actual failures, just the once canceled build-job.

**Comment by ferdnyc** [comment]
@jonoomph  Also, re `RESVG::resvg_NOTFOUND` on Windows: 

Is there a `resvg.dll.a` file anywhere on the system? (Ideally in `/usr/local/lib/`?) In theory that's what CMake **should** be picking up, to link the library into `libopenshot.dll` — the way it does with `libzmq.dll.a` and etc. But right now it's only finding `resvg.dll`.

It could be that it's _ignoring_ `resvg.dll.a` because I need to fix the find module, but I just want to double-check that it's _there_ before I try too hard to make it detect the file. :grin:

**Comment by ferdnyc** [comment]
Never mind, with my latest changes in http://gitlab.openshot.org/OpenShot/libopenshot/commit/290c7a7e84050c6d7d5d18a543e0245f77295557 the Windows builders appear to be happy linking with `resvg.dll` instead of the `.dll.a` file.

**Comment by ferdnyc** [comment]
And AppImages built with 22793e27457d932fa164090b086b024f411c30ed have libresvg.so linked properly! \o/ Now to actually test the color-inversion fix...

**Comment by ferdnyc** [comment]
@jonoomph  Whoop! Well, we're closer. Now I get a C++ traceback/crash in the AppImage, trying to drag an SVG title file from Project Files to the Timeline.

But I'm not sure that one's my fault, because this is the traceback:
```
QSslSocket: cannot resolve CRYPTO_num_locks
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve ERR_free_strings
QSslSocket: cannot resolve sk_new_null
QSslSocket: cannot resolve sk_push
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot resolve SSLeay_version
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
  /tmp/.mount_GcpFEu/usr/bin/libQt5Network.so.5 (                                           + 0xd745c)  [0x7f7b2597a45c]
  /tmp/.mount_GcpFEu/usr/bin/libQt5Network.so.5 ( QSslCertificate::fromData(QByteArray const&, QSsl::EncodingFormat)  + 0x25  )  [0x7f7b2597a665]
  /tmp/.mount_GcpFEu/usr/bin/libQt5Network.so.5 ( QSslCertificate::fromPath(QString const&, QSsl::EncodingFormat, QRegExp::PatternSyntax)  + 0x69a )  [0x7f7b2597ed6a]
  /tmp/.mount_GcpFEu/usr/bin/libQt5Network.so.5 (                                           + 0xec4e4)  [0x7f7b2598f4e4]
  /tmp/.mount_GcpFEu/usr/bin/libQt5Network.so.5 (                                           + 0xec840)  [0x7f7b2598f840]
  /tmp/.mount_GcpFEu/usr/bin/libQt5Network.so.5 ( QSslCertificate::QSslCertificate(QByteArray const&, QSsl::EncodingFormat)  + 0x78  )  [0x7f7b2597a1b8]
  /tmp/.mount_GcpFEu/usr/bin/libQt5Network.so.5 ( QSslConfiguration::QSslConfiguration()    + 0x39  )  [0x7f7b2597fe99]
  /tmp/.mount_GcpFEu/usr/bin/libQt5Network.so.5 (                                           + 0x796b3)  [0x7f7b2591c6b3]
  /tmp/.mount_GcpFEu/usr/bin/libQt5Network.so.5 (                                           + 0x81ff5)  [0x7f7b25924ff5]
  /tmp/.mount_GcpFEu/usr/bin/libQt5Network.so.5 ( QNetworkAccessManager::createRequest(QNetworkAccessManager::Operation, QNetworkRequest const&, QIODevice*)  + 0x2ec )  [0x7f7b258fd51c]
  /tmp/.mount_GcpFEu/usr/bin/libQt5Network.so.5 ( QNetworkAccessManager::get(QNetworkRequest const&)  + 0x14  )  [0x7f7b258fa164]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0xacdacb)  [0x7f7b1e801acb]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0xacdbe8)  [0x7f7b1e801be8]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0xaca280)  [0x7f7b1e7fe280]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0xacae91)  [0x7f7b1e7fee91]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0xacb9ee)  [0x7f7b1e7ff9ee]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0xac7075)  [0x7f7b1e7fb075]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0xa0685c)  [0x7f7b1e73a85c]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0x8f016a)  [0x7f7b1e62416a]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0x8f44ce)  [0x7f7b1e6284ce]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0x8f47f0)  [0x7f7b1e6287f0]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0x89b5e1)  [0x7f7b1e5cf5e1]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0x8ab582)  [0x7f7b1e5df582]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0x8aba11)  [0x7f7b1e5dfa11]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0x8d9969)  [0x7f7b1e60d969]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0x128fce1)  [0x7f7b1efc3ce1]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0x14c701f)  [0x7f7b1f1fb01f]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0x146d556)  [0x7f7b1f1a1556]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0x14cab1e)  [0x7f7b1f1feb1e]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0x14cac9e)  [0x7f7b1f1fec9e]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0x14cadd2)  [0x7f7b1f1fedd2]
  /tmp/.mount_GcpFEu/usr/bin/libQt5WebKit.so.5 (                                           + 0xca9af6)  [0x7f7b1e9ddaf6]
  [0x7f7ac7fff265]                        
---- End of Stack Trace ----
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function ERR_free_strings
QMutex: destroying locked mutex
Caught signal 11 (SIGSEGV)
---- Unhandled Exception: Stack Trace ----
zsh: segmentation fault (core dumped)  ./OpenShot-v2.4.4-dev2-1578555150-a8b65f57-f38389fc-x86_64.AppImage
```

And I happened to notice these messages in the builder logs of the last few linux builds (note the `WARNING`s):
```
      freeze:INFO Execution path: /home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/freeze.py
      freeze:WARNING /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: not found, skipping
      freeze:WARNING /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: not found, skipping
      freeze:WARNING /usr/lib/x86_64-linux-gnu/libthread-2.0.so: not found, skipping
<module 'cx_Freeze' from '/usr/local/lib/python3.4/dist-packages/cx_Freeze-4.3.4-py3.4-linux-x86_64.egg/cx_Freeze/__init__.py'>
Copying modules to openshot_qt directory: /home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot_qt
Loaded modules from openshot_qt directory: /home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot_qt
running build
running build_exe
```

Path/versioning issue on the linux builder, perhaps?

**Comment by ferdnyc** [comment]
Indeed, from exploring the AppImage I can say that it does _not_ contain `libssl.so.1.0.0` or `libcrypto.so.1.0.0`, but at least `_ssl.cpython-34m-x86_64-linux-gnu.so` is looking for them:
```sh
$ cd /tmp/.mount_avJWHX

$ ls usr/bin/*ssl*
usr/bin/_ssl.cpython-34m-x86_64-linux-gnu.so

$ ldd usr/bin/*ssl*
	linux-vdso.so.1 (0x00007ffc602dd000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f00f2980000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f00f27b7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f00f2c18000)
	libssl.so.1.0.0 => not found
	libcrypto.so.1.0.0 => not found
```

**Comment by ferdnyc** [comment]
> And I happened to notice these messages in the builder logs of the last few linux builds (note the `WARNING`s):

Hmm, those are `WARNING`s (instead of fatal errors) only in the wake of OpenShot/openshot-qt#3106, which was intended to make `freeze.py` more usable for _other_ developers / on _other_ systems — not to paper over issues on the build servers.

Maybe I should add a command-line flag that will make those `WARNING`s fatal again. We can use that on the GitLab CI platforms, to make sure that no incomplete builds sneak through.

**Comment by jonoomph** [comment]
@ferdnyc, here are those files on the Linux build server:
```
ubuntu@ip-172-30-0-113:/usr/bin$ ldd openssl
	linux-vdso.so.1 =>  (0x00007ffce7173000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f694bf57000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f694bb7a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f694b7b1000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f694b5ad000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f694c1b6000)
```

**Comment by jonoomph** [comment]
AppImages now launch, and **resvg** is updated, but I'm still seeing the inverted gradient colors. Hmmm... Can anyone else confirm?

**Comment by jonoomph** [comment]
:heavy_check_mark: Mac: **resvg** works nicely, supports alpha gradients, and all titles work (including the default font)
:heavy_check_mark: Windows: **resvg** also works correctly now
:x: Linux: **resvg** still produces inverted colors, but alpha gradients now work.

Screenshot from 2020-01-09 15-20-40

**Comment by jonoomph** [comment]
@ferdnyc Perhaps the Linux version of Qt5 is too old, and has some other issue. We are currently running: `qt5 version: 5.2.1` on it. I'm going to backup the Linux builder, and see if I can upgrade Qt5, sip, and the python3 bindings.

**Comment by ferdnyc** [comment]
@jonoomph Agreed, if it wasn't the image format, then I'm inclined to just blame Qt 5.2 in general.

**Comment by RazrFalcon** [comment]
@ferdnyc Do you convert produced image from ARGB_Premultipled to RGBA8888 manually? Maybe automatic conversion is broke in this version of Qt? I still insist that this issue is not related to `resvg`.

**Comment by ferdnyc** [comment]
> @ferdnyc Do you convert produced image from ARGB_Premultipled to RGBA8888 manually? Maybe automatic conversion is broken in this version of Qt? I still insist that this issue is not related to `resvg`.

I absolutely agree with you! Especially since it turns out that I'm an idiot. Twice over.

When I made the change to our resvg code, I fixed the image-_loading_ code, but missed that there was a copy-paste version of the exact same conversion code in `QtImageReader::GetFrame()`, the code that handles conversion of the image data for the previewer/encoder. _That_ was still using the old code.

So, it's fully expected that nothing would've changed in the AppImage builds made after my previous "fix" (which fixed only the wrong code, effectively). The commits I just pushed make the same change to the `GetFrame()` code, which is what matters. So, this _may_ be fixed "for real" now.

Of course, the build host is down for a failed update of Qt, since we were thinking that was the problem. So it'll be hard to confirm that immediately.

**Comment by ferdnyc** [comment]
What we do _now_, though, for the record, is this:

https://github.com/OpenShot/libopenshot/blob/175062913d18336ad17e1b341d22ef9e3292c537/src/QtImageReader.cpp#L219-L254

Ugh, that's almost impossible to read with GitHub's page formatting.

**Comment by ferdnyc** [comment]
Basically, we set up a buffer that's (now) explicitly in `QImage::Format_BRGA32_Premultiplied` format, and let resvg render into that. Later, no matter what the image format started as (in case we loaded it from a file, in which case it could be in arbitrary format), we unconditionally convert to `QImage::Format_RGBA8888`.

**Comment by ferdnyc** [comment]
So, I think we should hold off on this release for just around a week longer, based on what I've discovered today.

Let me preface this by saying that I've been sitting on it for _hours_, trying to figure out where I made some mistake or misinterpreted some data, because I didn't even believe it myself. I figured I must've made an error somewhere. But the more I test, the _more_ unbelievable the results get, and I've finally decided to accept that I might just be right about this.

Qt are _not_ kidding around, about the performance differences between various QImage formats.

The `argb-image-format` branch in my fork contains the `develop` branch code, with only _two_ changes:
1. I made the modification I mentioned above, to use `setOpacity()` instead of bit-hammering the alpha levels
1. I search-and-replaced every instance of `QImage::Format_RGBA8888` in the code with `QImage::Format_ARGB32_Premultiplied`.

Then I wrote some benchmark scripts, to compare the code on this branch to the modified `argb-image-format` code. At first the results were pretty inconclusive, it's not like just changing the image format magically made `GetImage()` noticeably faster, or anything. So I had to get more creative.

I created a _complex_ project in OpenShot, where "complex" means that from the very first frame, there are always FIVE tracks with video running on them, all with their Alpha properties set for semi-transparency, and with keyframed transforms constantly going on. There are videos rotating, other videos scaling and sliding around behind them, a couple of the middle videos shrink down and walk around the screen as they fade in and out of visibility... it's a chaotic, incomprehensible mess, in short.

I saved that project, removed the history from the file, and then ran Export time trials in the GUI. Using the same OpenShot code (the release branch over there), I `PYTHONPATH` loaded builds of both libopenshot branches' code, opened the saved project (set up for 1280x720 @ 30fps), and immediately performed an Export with the same parameters: Medium-quality MP4, video-only, frames 1-300, without GPU accel.

| branch | Time to export |
|----------|-----------------------------------------------------------------------------------------------------|
|`release-20200105` | 18.72 seconds :x: |
| `argb-image-format` | **13.14 seconds** :heavy_check_mark: |

Like I said, I didn't believe it either. So I modified my benchmark scripts to use the new project, and set them up to test the encode path specifically: create a Timeline, set up a Writer, and then repeatedly do `timeline.GetFrame(); writer.WriteFrame();` for each frame from 1-300, four times over. (So, the total export was 1200 frames.) 

Then I ran best-of-three timing trials between the two branches, now performing three tests:
1. Repeatedly `GetFrame(47); SaveFrame('/dev/null/')`; repeat 100 times 
2. `GetFrame()` a random frame#, `SaveFrame('/dev/null/')`; repeat 60 times 
3. The sequential `GetFrame()`->`WriteFrame()` test over frames 1-300 four times

(Each result is the best of three runs.)

| branch                    | Test 1                                            | Test 2 | Test 3 |
|--------------------------|-------------------------------------------|------------------|------------------|
|`release-20200105` | **`5.047s`** :heavy_check_mark: | `52.215s` :x: | `56.275s` :x: |
| `argb-image-format` | `5.307s` :x: | **`39.927s`** :heavy_check_mark: | **`32.642s`** :heavy_check_mark: |

I keep running it, and the results are the same: Whether in benchmarks or interactively, for complex compositing operations QImage/QPainter using `ARGB32_Premultiplied` is somewhere on the order of **THIRTY TO FORTY PERCENT** faster than `RGBA8888`.

Now, there's an obvious issue with this, currently: **The colors are all out of whack.** To complete the format-change, I have to go through the code, find all the places where we bit-hammer the image bytes directly, and reorder them from RGBA to ARGB. (Or, more likely, rewrite the code to use Qt's `qRgb()`, because it will conform to the image format automatically. So even if we were to change the format again in the future, the code wouldn't have to change.)

It'll take a bit of work, and a few days to get it right probably. But... I mean... it sounds _worth it_, no!?

**Comment by ferdnyc** [comment]
> The colors are all out of whack.

Actually, the funny thing is, that's only true of the **preview** widget. The exported colors are perfect, the way we deliver the image data to FFmpeg must be able to handle the format change.

I used [this technique](http://dericed.com/2012/display-video-difference-with-ffmpegs-overlay-filter/) to diff the results of both of the OpenShot exports above, and the image was solid gray (no differences at all) _except_ for one video I included that's cropped to a non-standard size of `430px × 720px`. That video makes OpenShot _very_ unhappy, and results in a several-pixels-wide band of video noise on its right edge. Because that area _was_ random noise, it didn't match up between the two videos, just like it wouldn't match up between two different exports from the SAME code.

But other than that, the output videos were 100% identical. One of them just got written 5½ seconds faster than the other.

**Comment by jonoomph** [comment]
@ferdnyc This sounds very promising indeed!!! Yes, let's hold off the release for a few more days and see how this turns out. :crossed_fingers: Please let me know when the branch is ready for some testing, and I'll give is a try on all 3 OSes.

**Comment by SuslikV** [comment]
> ..._except_ for one video I included that's cropped to a non-standard size of `430px × 720px`. That video makes OpenShot _very_ unhappy, and results in a several-pixels-wide band of video noise on its right edge...

Last time it was mentioned here: https://github.com/OpenShot/openshot-qt/issues/3152

**Comment by SuslikV** [comment]
Depending on how Preview looks for you, you may try to change the `windows/video_widget.py` of OpenShot by adding to `present()` function next code:
```
self.current_image.reinterpretAsFormat(QImage.Format_ARGB32_Premultiplied)
```

**Comment by ferdnyc** [comment]
> Depending on how Preview looks for you, you may try to change the `windows/video_widget.py` of OpenShot by adding to `present()` function next code:
> 
> ```
> self.current_image.reinterpretAsFormat(QImage.Format_ARGB32_Premultiplied)
> ```

Unfortunately we can't use that, as it's only present in Qt 5.9 and later. But `openshot::Frame::Save()` was also writing out color-swapped PNG files (just not color-swapped video frames), so I think it was purely a bug in libopenshot. That format should be the _default_ for any Qt image-processing functions, anyway, so I can't imagine openshot-qt would need to explicitly request it.

Regardless, the code wasn't coming together as quickly as I'd hoped, as our direct bit-access makes a format change somewhat complicated. So @jonoomph and I decided to postpone it for after the release. Once the release is done I'll get my in-progress changes into a more coherent state and create a branch off of `develop` in the project repo (or repos, if openshot-qt does also require changes), so that others can review and contribute.

**Comment by ferdnyc** [comment]
I did want to ask @jonoomph if he's seen #416, though, and might want to incorporate it into the 0.2.4 release — as I said in the PR, it made a _**huge**_ difference in preview playback on my system, and we've had more reports come in (OpenShot/openshot-qt#965) just today about poor preview performance.

**Comment by jonoomph** [comment]
Looking at https://github.com/OpenShot/libopenshot/pull/416 now. I'm a little concerned about the memory requirements of this change. I'm gonna test it real quick though.

**Comment by jonoomph** [comment]
Okay, in my tests this worked great. About to merge for final release

**Pull request merged**
