### PR TITLE
Properly set test media files path, fixes #36

### LINKED ISSUE #36: Tests fail: 'No Reader has been initialized for this Clip' and 'File could not be opened'
Hi,
I'm  unable to make tests pass on my system. I just ran `cmake . && make && tests/openshot-test` on an  up-to-date git clone and I see the following:

```
----------------------------
     RUNNING ALL TESTS
----------------------------
/tmp/libopenshot/tests/Clip_Tests.cpp:50:1: error: Failure in Clip_Constructor: Unhandled exception: No Reader has been initialized for this Clip.  Call Reader(*reader) before calling this method.
/tmp/libopenshot/tests/Clip_Tests.cpp:205:1: error: Failure in Clip_Effects: Unhandled exception: No Reader has been initialized for this Clip.  Call Reader(*reader) before calling this method.
/tmp/libopenshot/tests/ImageWriter_Tests.cpp:36:1: error: Failure in ImageWriter_Test_Gif: Unhandled exception: File could not be opened.
/tmp/libopenshot/tests/FFmpegReader_Tests.cpp:41:1: error: Failure in FFmpegReader_GetFrame_Before_Opening: Unhandled exception: File could not be opened.
/tmp/libopenshot/tests/FFmpegReader_Tests.cpp:52:1: error: Failure in FFmpegReader_Check_Audio_File: Unhandled exception: File could not be opened.
/tmp/libopenshot/tests/FFmpegReader_Tests.cpp:82:1: error: Failure in FFmpegReader_Check_Video_File: Unhandled exception: File could not be opened.
/tmp/libopenshot/tests/FFmpegReader_Tests.cpp:120:1: error: Failure in FFmpegReader_Seek: Unhandled exception: File could not be opened.
/tmp/libopenshot/tests/FFmpegReader_Tests.cpp:177:1: error: Failure in FFmpegReader_Multiple_Open_and_Close: Unhandled exception: File could not be opened.
/tmp/libopenshot/tests/FFmpegWriter_Tests.cpp:35:1: error: Failure in FFmpegWriter_Test_Webm: Unhandled exception: File could not be opened.
/tmp/libopenshot/tests/FrameMapper_Tests.cpp:180:1: error: Failure in FrameMapper_resample_audio_48000_to_41000: Unhandled exception: File could not be opened.
/tmp/libopenshot/tests/Timeline_Tests.cpp:88:1: error: Failure in Timeline_Check_Two_Track_Video: Unhandled exception: No Reader has been initialized for this Clip.  Call Reader(*reader) before calling this method.
/tmp/libopenshot/tests/Timeline_Tests.cpp:210:1: error: Failure in Timeline_Clip_Order: Unhandled exception: No Reader has been initialized for this Clip.  Call Reader(*reader) before calling this method.
/tmp/libopenshot/tests/Timeline_Tests.cpp:438:1: error: Failure in Timeline_Effect_Blur: Unhandled exception: No Reader has been initialized for this Clip.  Call Reader(*reader) before calling this method.
FAILURE: 13 out of 74 tests failed (13 failures).
Test time: 0.33 seconds.
----------------------------
```

### PR DESCRIPTION
**Pull request by sbraz**
This overrides TEST_MEDIA_PATH so that it is no longer set to
"../../src/examples/"
@jonoomph

### CODE REVIEW

**Comment by sbraz** [comment]
@jonoomph can you please look at this?

**Comment by jonoomph** [comment]
Hi, sorry this took so long for me to get too. =) I'm happy to merge this once it's been rebased off the latest version and verified again. Thanks

**Comment by sbraz** [comment]
@jonoomph rebased

**Comment by jonoomph** [comment]
Thanks again! Merged.

**Pull request merged**
