### PR TITLE
free cache in FrameMapper::Close()

### PR DESCRIPTION
**Pull request by ckirmse**
- this hugely reduces the memory used by rendering a timeline
  with a lot of clips
- could be related to issue #239

### CODE REVIEW

**Comment by jonoomph** [comment]
This looks good to me! I'm gonna test it out real quick though.

**Comment by jonoomph** [comment]
LGTM! Worked great.. nice fix!

**Comment by ferdnyc** [comment]
> * could be related to issue #239

I suspect it's not, only because `Example.cpp` only contains a single clip, and (obviously, therefore) doesn't call `Close()` until the end of the encode process.

It's still a great fix, and hopefully will have some effect on OpenShot/openshot-qt#2811, but #239 here can't really be `Close()`-related/dependent.

**Comment by ferdnyc** [comment]
Oh, wait, _FrameMapper_... not the Reader. Whoops. Ignore my previous comment, then. :confused:

**Comment by ferdnyc** [comment]
Unfortunately, though, this change does not reduce the out-of-control memory growth observed in #239. :disappointed:

**Comment by ferdnyc** [comment]
Oh, wait... no, yes it does! At least when the hardware decoder is enabled, yes. Resident memory consumption stays at around 800MB constant! Killer fix, @ckirmse ! :+1: 

I'll do a clean rebuild and double-check whether the software-decoder path is unaffected, as it seemed to be in my previous test.

**Comment by ferdnyc** [comment]
Huh. So, this is odd. With this fix in place, the hardware-decoded path is indeed fixed. But, with the hardware decoder disabled, the `openshot-example` process grows at a constant rate throughout the entire export process. There's still a leak in the software decoder path, looks like.

**Comment by ckirmse** [comment]
Is your test a single clip on a timeline? Because due to the frame caches, generally speaking the memory usage will go up throughout the processing of a clip, up to the max size of the frame caches. I haven't looked at the frame cache size limits personally.

**Comment by ferdnyc** [comment]
> Is your test a single clip on a timeline? Because due to the frame caches, generally speaking the memory usage will go up throughout the processing of a clip, up to the max size of the frame caches. I haven't looked at the frame cache size limits personally.

No timeline at all, `Example.cpp` just uses a single `FFMpegReader` to generate frames that it dumps into an `FFMpegWriter`.

(I've updated my previous comment since posting it.)

**Comment by ckirmse** [comment]
fwiw I'm using the software decoding path and I tested a timeline with this fix that had 137 clips (each about 10s long) and memory did not climb beyond a fixed amount right at the beginning (memory usage of the process never went over 900MB).

**Comment by ferdnyc** [comment]
> fwiw I'm using the software decoding path and I tested a timeline with this fix that had 137 clips (each about 10s long) and memory did not climb beyond a fixed amount right at the beginning (memory usage of the process never went over 900MB).

Wow, that's amazing! It sounds like this will go a long way towards addressing the process memory-growth I documented in OpenShot/openshot-qt#2811 then.

**Comment by ferdnyc** [comment]
Huh! Well, this is very screwy.

I was trying to run `openshot-example` under `memusage` so I could generate graphs of the memory growth like I did over in OpenShot/openshot-qt#2811 , and what I've discovered is that _this_ leak disappears when the process is shimmed by `memusage`. 

I have the **OLD** code (git 9ffd6a6, specifically) checked out, and the exact same `src/openshot-example` binary will grow nonstop if I just run it in the shell. But, `memusage -p /tmp/old.png -t -T -x 1200 -y 800 src/openshot-example` exhibits no memory growth, the graph looks like this:
old

(Which is also how the graph would look when _not_ running under memusage, with this fix applied.)

So, turns out this one's a bit of a heisenbug after all, which (partly) explains my earlier confusion. (The rest of the explanation is that I'm me, so confusion is expected.)

**Pull request merged**
