### PR TITLE
Update readme to use markdown and update copyright to 2019

### PR DESCRIPTION
**Pull request by jeffski**
Giving the README file some love and formatting using markdown. Also updated copyright dates to 2018.

### CODE REVIEW

**Comment by RichiCoder1** [comment]
Endorse! If only so when I wanna view docs on the go, I don't have to delete the `>` character from the (admittedly dated) libopenshot docs link :)

**Comment by DylanC** [comment]
@jonoomph - I know its small but can we merge this in?

**Comment by jeffski** [comment]
Happy New Year! I have updated the date to 2019. Also rebased develop so everything is up to date and changed the base branch to merge to develop instead of master.

**Comment by peanutbutterandcrackers** [comment]
@jeffski - Great! Happy New Year to you too! I just remembered this other PR at openshot-qt front https://github.com/OpenShot/openshot-qt/pull/1467 that has this neat feature that causes the year to pretty much update automatically. Could a similar thing be done here as well?

**Comment by peanutbutterandcrackers** [comment]
@jeffski - Great! Happy New Year to you too!

**Pull request merged**
