### PR TITLE
Upgrade bundled jsoncpp to 1.8.4

### PR DESCRIPTION
**Pull request by ferdnyc**
This PR replaces the entire `thirdparty/jsoncpp` directory with an updated version of the codebase, generated from a checkout of official [open-source-parsers/jsoncpp@5b91551f39](https://github.com/open-source-parsers/jsoncpp/tree/5b91551f3944d69e0090d6b6528852207de78078).

The new `thirdparty/jsoncpp` directory was generated using the jsoncpp project's `amalgamate.py` tool, which condenses the library down to a single C++ source file and two headers, making it easier to incorporate into libopenshot. The build is adjusted to match.

This upgrade is necessary because the previously bundled version does not support the new `Json::CharReader` class, which in recent versions replaces the now-deprecated `Json::Reader`. When building with a recent system jsoncpp (or, now, with this bundled version), the compile process emits a ton of deprecation warnings about `Json::Reader` being deprecated.

This PR does not _fix_ those warnings (that'll be a separate PR), but it is necessary as a prerequisite if we're going to merge those fixes.

The LICENSE for jsoncpp (included) has changed some since the previous version, but hopefully not in ways that should cause us any trouble. Recognizing that blanket statements of releasing something to the "public domain" are not recognized by law in some regions, the authors have chosen to dual-license the code as _either_ public domain, or the GPL-compatible MIT license.

### CODE REVIEW

**Comment by ferdnyc** [comment]
Excellent. Now, [thanks to Travis](https://travis-ci.org/OpenShot/libopenshot/jobs/548007543), all-y'all can enjoy the deprecation warnings that I've been staring at for months. :laughing: (But only until #256 is merged.)

**Comment by jonoomph** [comment]
Merging this into a different branch... to run through the builders first

**Comment by jonoomph** [comment]
Looking good so far!

**Comment by jonoomph** [comment]
I'm gonna try rebasing this back to develop (fingers crossed)

**Comment by jonoomph** [comment]
Nope, making a new PR

**Comment by ferdnyc** [comment]
:+1:  Whatever works!

I think one way to branch-test a PR would be to "clone" the PR's commits into a new branch. You'd start by checking it out on the command line. (The [`hub` command](https://github.com/github/hub) add-on from GitHub is great for that, you just `hub pr checkout 256` in your local repo clone and bingo-bango, it sets everything up automatically.) Then, you can create a new branch (`git checkout -b test256`) with the same history, and push it up to the repo (`git push -u $remotename test256`) as its own branch, without affecting the original PR.

..._"Should"_ work, tho I've never tried it.

**Pull request merged**
