### PR TITLE
CMake: Add Features for docs, unit tests

### PR DESCRIPTION
**Pull request by ferdnyc**
- A new CMake option, ENABLE_TESTS, is created and defaults ON; pass `-DENABLE_TESTS=0` to disable. (Legacy `-DDISABLE_TESTS=1` will also override)
- Target info for docs and tests is shown in the FeatureSummary
- UnitTest++ is now `RECOMMENDED`, not `REQUIRED`, since libopenshot can be built without running unit tests

I also briefly broke `FindUnitTest++.cmake`, at one point completely changed the name to `FindUnitTestCpp.cmake`, and then ended up restoring the original name.

(There's a bug in CMake that prevents certain features of `FindPackageHandleStandardArgs()` from being used with module names that contain regular expression special characters (like `+`) — I actually submitted a change to CMake that _fixes_ that issue, which [was merged](https://gitlab.kitware.com/cmake/cmake/merge_requests/4266) so in the future it won't be a concern. But since we support older releases, simplest solution is to just avoid making use of the feature (`FOUND_VARIABLE`) in question, which is what the new code does.)

By way of penance, when I restored the original module name I also added `pkg-config` support, so if UnitTest++ is installed in a standard system location (or if its `pkgconfig` directory location is added to the list of paths in the `PKG_CONFIG_PATH` environment variable) then `FindUnitTest++.cmake` will pick up a `UnitTest++.pc` file and import that info into the build environment.

No `IMPORTED` targets yet, though that's still on my goals list for this PR before merging. If it seems like it's just not gonna happen, I'll merge without and do that some time in the future.

The same old (environment,cache) variables will still work to set its path, but the PREFERRED way of specifying the location of UnitTest++ is by adding a `-DUnitTest++_ROOT=/path/to/unittest++` argument to the CMake command line. <code><var>pkgname</var>_ROOT</code> variables are handled with extra intelligence by CMake 3.12+, and the Find module (most, if not all, of our find modules now) now has forward-compatibility code that explicitly looks for those variables, so they'll work on older versions as well.

### CODE REVIEW

**Comment by ferdnyc** [comment]
<details>
<summary> CMake 3.16: <code>cmake ..</code> in build directory...</summary>

(Some output omitted)
<pre><code>
-- Displaying feature summary

Build configuration:
-- The following features have been enabled:

 * Documentation, Build API documentation with 'make doc'
 * Testrunner, Run unit tests with 'make test'
 * Unit tests, Compile unit tests for library functions

-- The following OPTIONAL packages have been found:

 * cppzmq
 * PythonInterp (required version >= 3)
 * PythonLibs (required version >= 3)
 * Ruby
 * Doxygen
 * PkgConfig
 * ImageMagick

-- The following REQUIRED packages have been found:

 * JsonCpp
 * Qt5Widgets
 * Qt5Core
 * Qt5Gui
 * Qt5Network (required version >= 5.12.5)
 * Qt5Multimedia
 * Qt5MultimediaWidgets
 * Qt5
 * FFmpeg
 * Threads
 * OpenMP
 * ZeroMQ
 * SWIG (required version >= 3.0)
 * UnitTest++
 * OpenShotAudio (required version >= 0.1.8)

-- The following features have been disabled:

 * IWYU (include-what-you-use), Scan all source files with 'iwyu'

-- The following OPTIONAL packages have not been found:

 * RESVG
</code></pre></details>

<details>
<summary> CMake 3.2: <code>cmake32 ..</code> in build directory...</summary>

(Some output omitted)
<pre><code>
-- Displaying feature summary

Build configuration:
-- The following features have been enabled:

 * Documentation , Build API documentation with 'make doc'
 * Testrunner , Run unit tests with 'make os_test'
 * Unit tests , Compile unit tests for library functions

-- The following OPTIONAL packages have been found:

 * cppzmq
 * PythonInterp (required version >= 3)
 * PythonLibs (required version >= 3)
 * Ruby
 * Doxygen
 * PkgConfig

-- The following REQUIRED packages have been found:

 * JsonCpp
 * Qt5Widgets
 * Qt5Core
 * Qt5Gui
 * Qt5Network (required version >= 5.12.5)
 * Qt5Multimedia
 * Qt5MultimediaWidgets
 * Qt5
 * FFmpeg
 * Threads
 * OpenMP
 * ZeroMQ
 * SWIG (required version >= 3.0)
 * UnitTest++
 * OpenShotAudio (required version >= 0.1.8)

-- The following features have been disabled:

 * IWYU (include-what-you-use) , Scan all source files with 'iwyu'

-- The following OPTIONAL packages have not been found:

 * ImageMagick
 * RESVG
</code></pre></details>

If `-DDISABLE_TESTS=1` or `-DENABLE_TESTS=0` is passed on the command line, the disabled features output changes to:
```
-- The following features have been disabled:

 * IWYU (include-what-you-use), Scan all source files with 'iwyu'
 * Unit tests, Compile unit tests for library functions
```
And the 'Testrunner' target info is not shown at all.

**Comment by ferdnyc** [comment]
Oh, I forgot to mention: if pkg-config is used to configure UnitTest++, it'll also pick up and report the version during CMake's generation process:

<pre><code>
cmake -DCMAKE_BUILD_TYPE=Release -DOpenShotAudio_ROOT=../../libopenshot-audio/build/dist/ -DRESVG_ROOT=/home/ferd/rpmbuild/REPOS/resvg/ ..
-----------------------------------------------------------------
          Welcome to the OpenShot Build System!

CMake will now check libopenshot's build dependencies and inform
you of any missing files or other issues.

For more information, please visit <http://www.openshot.org/>.
-----------------------------------------------------------------
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

Generating build files for OpenShot with CMake 3.16.4
  Building libopenshot (version 0.2.4)
  SO/API/ABI Version: 18

-- Found ImageMagick: /usr/lib64/libMagick++-6.Q16.so (found version "6.9.10-86") 
-- Found OpenShotAudio: /home/ferd/rpmbuild/REPOS/libopenshot-audio/build/dist/lib64/
libopenshot-audio.so (found suitable version "0.1.9-dev1", minimum required is "0.1.9") 
-- Looking for system JsonCpp
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3") 
-- Found jsoncpp: /usr/include  
[...]
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.15") found components: doxygen dot 
-- Found DOXYFILE_IN: /home/ferd/rpmbuild/REPOS/libopenshot/Doxyfile.in  
-- Doxygen found, documentation target enabled
<b>-- Found UnitTest++: /usr/lib64/libUnitTest++.so (found version "2.0.0")</b>
-- Tests enabled, test executable will be built as tests/openshot-test
-- Cmake 3.11+ detected, enabling 'test' target
-- Displaying feature summary

Build configuration:
-- The following features have been enabled:

 * Documentation, Build API documentation with 'make doc'
 * Testrunner, Run unit tests with 'make test'
<b> * Unit tests, Compile unit tests for library functions</b>

-- The following OPTIONAL packages have been found:

 * cppzmq
 * RESVG
 * PythonInterp (required version >= 3)
 * PythonLibs (required version >= 3)
 * Ruby
 * Doxygen
 * PkgConfig
 * ImageMagick

-- The following RECOMMENDED packages have been found:

<b> * UnitTest++
   Unit testing framework</b>

-- The following REQUIRED packages have been found:

 * JsonCpp
 * Qt5Widgets
 * Qt5Core
 * Qt5Gui
 * Qt5Network (required version >= 5.13.2)
 * Qt5Multimedia
 * Qt5MultimediaWidgets
 * Qt5
 * FFmpeg
 * Threads
 * OpenMP
 * ZeroMQ
 * SWIG (required version >= 3.0)
 * OpenShotAudio (required version >= 0.1.9)

-- The following features have been disabled:

 * Coverage, analyze test coverage and generate report
 * IWYU (include-what-you-use), Scan all source files with 'iwyu'

-- Configuring done
-- Generating done
-- Build files have been written to: /home/ferd/rpmbuild/REPOS/libopenshot/build
</code></pre>

**Comment by jonoomph** [comment]
@ferdnyc Any risk of this breaking on build servers? Should we test on a dedicated branch, or has that already been done? I'm okay merging if you feel it's safe though.

**Comment by ferdnyc** [comment]
@jonoomph No significant danger. I tested the configs locally with CMake  3.2, as well as Fedora's current 3.16.

**Comment by ferdnyc** [comment]
I SHOULD check whether there are any changes to `.gitlab-ci.yml` that should go with this. I'll do that this evening, then merge.

**Comment by ferdnyc** [comment]
I'm actually going to merge this, because I just experimentally discovered that on Windows, trying to build _without_ this change will fail if UnitTest++ is not installed. With these changes, it's correctly skipped. (The unit tests are simply disabled, as intended.)

Any changes to the Gitlab builder configs should be optional, not required, so those can happen separately.

**Comment by ferdnyc** [comment]
(I will of course check on the Gitlab builders now...)

**Comment by ferdnyc** [comment]
Everything configured fine. Amusingly, the presence of a version number in the discovery logs indicates that the macOS builder used `pkg-config` to discover `libunittest++.dylib`:
```
-- Found UnitTest++: /usr/local/lib/libUnitTest++.dylib (found version "2.0.0") 
```
but the _Linux_ builder **DIDN'T**:
```
-- Found UnitTest++: /usr/lib/libunittest++.a  
```
...I don't even know _what_ to make of that.

(Maybe it's because Linux has (only?) the static-lib version of UnitTest++, not the shared lib. Or it could be that the name is different — on my Fedora system, the shared lib is named `libUnitTest++.so.2`, so the Find module looks for a pkg-config file `UnitTest++.pc`. Maybe it was named `unittest++.pc` on ancient Ubuntu. :man_shrugging: )

Regardless, doesn't affect anything with the build.

**Pull request merged**
