### PR TITLE
Reorganize repo (headers moved to src/, bindings/ and examples/ made root-level dirs) & update build system

### LINKED ISSUE #471: Developers RFC: Includes reorganization
I've been thinking about a major reorg to the repo header file management, for a couple of reasons (which I'll explain). So I wanted to post my thoughts here and invite feedback/commentary from both the other libopenshot developers, _and_ our library consumers. (Though my current plans have considered the impact on the latter, and include pains taken to keep it to a minimum, at least short-term.) As well as, of course, anyone else who's interested and can offer any relevant insights or experience.

#### Motivations
My concerns regarding the current header setup are,
1. As I detail in #469, relative include paths can be problematic. And relative include paths that _leave_ the root of the source tree can be disastrous. Depending where that path is anchored, you could end up with a file from almost anywhere. <code>#include "../../../include/<var>anything</var>"</code> is just a bad idea and a recipe for problems.
1. _Without_ the relative paths, all we have are bare filenames, and that's a poor way to organize a set of API headers. `#include "Color.h"`? Do you know how many possible matches there could be for that name?<sup>**1**</sup>
1. Related to the previous item: The include paths used by library consumers look _nothing_ like the paths we use internally. That means there are aspects of our code that are simply not tested at any point during development. In fact, as internal developers we never even get a _glimpse_ of what it's like to code against libopenshot as an external consumer. That's a troubling hole in the development plan.
1. The whole `src/` vs. `include/` structure for a codebase is pretty dated, these days, and it shows in the hoops we have to jump through to make it work. The CMake/Qt `AUTOMOC`, for example, by default will scan for and process Qt classes in any implementation-header file pair it finds in a directory tree — but it expects to find both files together. It took manually adding all of the Qt headers as _source_ files of the library, in the CMake configs, to get `AUTOMOC` working with the current organization. (That setup _works_ fine, but it was an extra PITA that could've been avoided.)
1. On a personal note, I find it particularly hard to edit a split directory structure like we use. It's pretty rare that editing a particular `.cpp` file doesn't send me off to open its header file as well, or vice versa. Most editors don't make that very convenient — not nearly as convenient as having the files side-by-side would be, anyway.

#### Proposals
So, given all that, I'm actually considering a PR that would go one of two very _different_ routes. And I'll say up front, I vastly prefer the first option. But if it's objectionable for some reason, the second would be my compromise proposal. I'm advocating that we do **one of** the following...
1. **Move all of the headers into the `src/` directory, keeping the directory hierarchy the same.** So, each <code><var>filename</var>.h</code> file would be located in the same directory as the corresponding <code><var>filename</var>.cpp</code> file, and it would be included in the internal code as just `#include "Frame.h"` or `#include "Qt/VideoRenderer.h"`. (My concerns about generic pathnames are lessened considerably when the files are all _in_ or _below_ the source file tree, rather than having to move _upwards_ out of it.) 
1. **Create a subdirectory `include/openshot/`, and move all of the headers inside of that directory.** The build-time include path would be set to `${PROJECT_SOURCE_DIR}/include`, and headers would be included by internal source code using e.g. `#include "openshot/Frame.h"` or `#include "openshot/Qt/PlayerDemo.h"`.

#### Discussion
What I like about the first option is that it addresses Motivation points 1, 4, and 5, while as I mentioned greatly lessening my concerns regarding point 2. The only box it doesn't tick is point 3.

The _second_ option is actually **primarily** focused on Motivation point 3, and it also addresses point 2 much better than the alternative, while also covering point 1. Unfortunately it's no relief at all when it comes to points 4 and 5. Still, the earlier Motivation items are a much higher priority, since 4 and 5 are mostly just about convenience/preferences.

##### Header installation
The primary motivation for separating headers from source code tends to be packaging/installing, since (in theory) it's easiest if the install can copy `${PROJECT_SOURCE_DIR}/include/` to `/usr/local/include/libopenshot/` or wherever, and done — there's your header export. Easy-peasy.

Nice theory, but CMake doesn't work that way. It _already_ doesn't work that way. Currently we're installing the headers from CMake with the following command:
```cmake
install(DIRECTORY ${CMAKE_SOURCE_DIR}/include/
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/libopenshot
  FILES_MATCHING PATTERN "*.h")
```
That could be changed to `install(DIRECTORY ${CMAKE_SOURCE_DIR}/src/ ...)` and it would work **_exactly_ the same**, thanks to the `FILES_MATCHING PATTERN "*.h"`. There is simply no compelling reason why headers need to be segregated from their source files, anymore.

##### External API consumers
Regardless which of these plans we go with, my _intention_ is that when the headers are **installed**, they go into a new `include/libopenshot/` subdirectory named `openshot`, and **EXTERNAL** libopenshot developers would access the headers using <code>#include <openshot/<var>Class</var>.h></code> statements, protecting them from filename clashes when using our API.

(It also means that every class is included via a header path with the **exact** same, complete name — including the namespace. That's not only safer, it actually makes **_more_** sense.) If we were to go with proposal 2, then internally we'd be doing much the same. (We'd probably just use double-quoted names instead of angle-bracketed names, since the headers aren't system headers when not installed.)

##### Unprefixed include deprecation
To ease the transition to the new paths, and so that we don't break every external API consumer's code completely, what I'd want to do (and again, this goes for **either** internal reorg proposal) is set up a transitional set of "shim" files that emit deprecation warnings. Here's how that would look:

* All of the new headers get installed into <code><var>prefix</var>/include/libopenshot/openshot/</code>.
* The include path for the library is defined as <code>prefix</code>/include/libopenshot</code>, same as always.
* API users are _meant_ to change their code to the newly-canonical `#include <openshot/Frame.h>` form.

But since that'll take some time, for the next couple of releases or so, a set of "relocation" headers would also be installed one level up, matching the _previous_ hierarchy. For every "real" header <code><var>prefix</var>/libopenshot/openshot/<var>(\*/)filename</var>.h</code>, there'd be a corresponding "redirect" header.

A redirect header <code><var>prefix</var>/libopenshot/FOO.h</code> would look roughly like this:
```h
#ifndef OPENSHOT_REDIRECT_HAVE_WARNED
#define OPENSHOT_REDIRECT_HAVE_WARNED

OPENSHOT_DEPRECATED_MSG("Unprefixed \"CLASS.h\" includes are deprecated and will
be removed in a future release. Use \\#include <openshot/CLASS.h> style includes instead.")
#endif

#include "./openshot/FOO.h"
```
With some macro magic borrowed from Qt or the like to emit deprecation messages, that should make the reorganization transparent for external API users and prevent their projects breaking, while still making sure to inform them of the change and give them time to update their code.

##### The bindings
Even though with #469 I've fixed the bindings so that they _could_ live anywhere, in any of these scenarios, my thinking is that they'd move out of the `src` directory completely, probably into a `bindings/` directory at the top level of the repo, alongside `src/` and possibly `include/`. There's no reason to have them buried so deeply that the Python module builds as `src/bindings/python/openshot.py` _inside_ the build dir.

Especially since we _**really**_ need to start building `openshot.py` / `_openshot.so` as a Python _package_, complete with metadata that OpenShot can probe for as a dependency, and so `setuptools` can install it instead of us having to play stupid distro tricks in CMake. That structure will most likely add one additional directory level.

The Ruby bindings, by the same token, should really be packaged as a rubygem. (Though I don't think that'll require a subdirectory.)

##### The rest of `src/`
Who needs it at all? To my mind, the "`src/`" distinction is artificial and meaningless anyway. IMHO `src/` should really be called `lib/` or `libopenshot/`, since that's what it's the source _**for**_, specifically. In fact, I'd even be in favor of renaming it, and rearranging the repo structure so that...
* `src` renamed to `/libopenshot/`
* `src/examples/` moved to `/examples/`
* `src/Qt/demo/` also moved to `/examples/`
* `src/bindings/` moved to `/bindings/`, as mentioned
* The test media files in `src/examples/` moved to a new `/data/`, since they're not the source for anything.
* (Possible/worth exploring...)
    * `src/effects/` gets relocated to `/effects/` and built as a distinct subdirectory with its own `CMakeLists.txt`, which would put us in a much better position to finally begin incorporating @kirillmakhonin's DynamicEffects proposal from #345. (At least in the short term the effects would still get linked into `libopenshot.so` same as ever, only the build steps would change.)
    * We unbundle `jsoncpp` from `/thirdparty/jsoncpp/`, since it's weird that this _one_ arbitrary dependency, of all the libraries we require, is bundled in an out-of-date state inside our repo.
    * We _bundle_, instead, `libopenshot-audio` as `/extern/libopenshot-audio/` — not by cloning its source there, but as either a Git submodule or a CMake external project. (Either of which would give the option of downloading the source to be compiled during the libopenshot build process.) We could then support installing and packaging them together, so they're _conceptually_ a single library that just happens to be split into two separate loadable object files.

That last item is getting way outside the scope of this proposal, but it would (for example) make it workable to finally begin doing libopenshot CI builds on Windows and MacOS. Whereas today we only test on Linux because it's the only platform where we can pull `libopenshot-audio` in from the daily PPA as a dependency.

#### Keeping up with the Indianas
In proposing any of this, I'd be remiss if I didn't at least make a cursory survey of the repo organization in use by other projects, to get a feel for what others have deemed appropriate for _their own_ situation, at least. (Though whether or how that would apply to _ours_ is certainly debatable.) Looking over some long-lived, active codebases that we'd be familiar with...
1. **JUCE:** First, close to home, JUCE installs as a collection of modules, each a directory containing a multi-level hierarchy of `.cpp` and corresponding `.h` files side-by-side.
1. **Qt:** Maintains a separate Git repo per module (QtCore, QtMutimedia, etc.), where each repo houses multiple libraries, plugins, and tools. They do use a `/src/` directory, but it contains subdirectories per logical build unit, each containing `.cpp` and `.h` files side-by-side.
1.  **FFmpeg:** Repo has a top-level directory per library (`libavcodec`, `libavformat`, etc.) and one called `fftools` containing the commandline sources. Each directory contains `.c` and `.h` files side-by-side.
1. **ImageMagick:** Nearly identical to FFmpeg. Top-level `Magick++`, `MagickWand`, etc. dirs, plus `uilities` for the commandline sources and man page sources. For the libraries,
    * `MagickWand` and `MagickCore` contain `.c` and `.h` files side-by-side
    * `Magick++` contains a `lib/` subdir holding `.cpp` files, and a `Magick++` subdir beneath _that_ containing all the headers, which is a hybrid option I'd meant to raise — we could have an `openshot/` header dir inside the **source** tree, instead of in `/include/`, so that `Frame.cpp` would `#include "openshot/Frame.h"` the same way external API callers would.
1. **VLC:** The odd bird of the bunch. Has both `src/` and `include/` as toplevel repo dirs. Maintains a separation between public and private headers — `src/` contains a hierarchy of `.c` files, some of which have private headers alongside. Includes in source files are a complex mix of `#include <vlc_codec.h>` public-header includes (from `/include/vlc_codec.h`), `#include "something.h"` local private-header includes, and `#include "../somethingelse.h"` relative private-header includes. Looks confusing as all getout, TBH.

#### Conclusion
So, there you have it. I actually found it _hard_ to locate an example of another project with any sort of `include/` directory **at all**, until VLC — if I hadn't thought to check what the French have been up to, I wouldn't have found a single example.

Sorry this turned into such a tome, but I wanted to be comprehensive. High-level summary maybe forthcoming if anyone wants, though of course you'd have to read all the way down to here before you'd see that offer. I'm a stinker. 

**CC:** @jonoomph @eisneinechse @SuslikV @musteresel @mkarg @DylanC @N3WWN @jeffski @ckirmse @chad3814 , kirillmakhonin who I already tagged earlier, and of course whichever really obvious user I'll end up having left out, so I can feel guilty later.

#### Notes
1. I can give you some idea: On my system, there are at least _six_ completely distinct `Color.h` files, out of 29 total matches for that filename (many are duplicates) — and that's **_with_** the capital 'C'! If I include `color.h`, that number rises to 58 total file matches, representing roughly 15 distinct files.

### PR DESCRIPTION
**Pull request by ferdnyc**
### REALLY IMPORTANT BIT

This PR is a resurrection of #504. The headline is that it moves all of libopenshot's headers out of the `include/` directory, and places them all in the `src/` directory alongside their implementation files. (The hierarchy is preserved: `include/Qt/*` moves to `src/Qt`, etc.) Meanwhile, the `bindings/` and `examples/` subdirectories are moved out of `src/` and placed at the root of the repo.

To read my justification for this change, along with reasons why I feel it's worth the upheaval it will cause, see my initial proposal in issue #471.

(This PR thus: Fixes #471, though that issue's already been closed by the Stale bot.)

#### Slightly less important bit (with some additional details)

The original PR also had to be closed, but in that case it was due to the difficulties we encountered trying to reconcile it with the current repo state in the wake of several weeks' worth of other changes to `develop`. As such, _this_ PR is being fast-tracked to merge _**quickly**_, pretty much as soon as it passes the necessary checks (and before any other changes land in `develop`). The hope is that this will help prevent the conflicts that would inevitably arise if any other changes are merged. @jonoomph has already signed off (in #504) on the _concept_ of these changes, it's just a question of creating the opportunity to make them.

Given that this PR touches very nearly every source file in the repository, merging it will most likely result in conflicts appearing in many or all of the _other_ open PRs. That's unfortunate, but also unavoidable given the nature of these changes.

After the merge, I will _attempt_ to resolve any open PR conflicts on behalf of their submitters. There may be some I'm not able to sort out on my own, though, and I'll be forced to leave their resolution to the author. In addition, if anyone has local changes on a PR branch that they haven't yet pushed to Github, merging this PR will probably make that process messier and more complicated. Either way, I apologize in advance for this one-time disruption.

Just wanted to preemptively bring this impending codepocalypse to everyone's attention. **#YouHaveBeenWarned**

Courtesy-tagging submitters of all open PRs: @ckirmse @jonoomph @kartchnb @musteresel @chad3814 @PhysSong @aopa-frogslayer @kirillmakhonin. 

#### Not at all important bit (with excessive details regarding the specifics of the PR)

From the original PR description:

> This implements the proposal I made in #471, that header files live in the `src/` directory alongside their `*.cpp` files, rather than being kept in an `include/` directory.
> 
> - Move all `/include/**/*.h` to `/src/...` (with same hierarchy)
> - Move `/src/examples` to `/examples`
> - Move `/src/Qt/demo` to `/examples/qt-demo`
> - Move `/src/bindings/` to `/bindings`
> - Adjust source files (far fewer relative includes):
>   - `/src/**/*.cpp`
>   - `/src/**/*.h`
>   - `examples/**/*.cpp`
>   - `tests/**/*.cpp`
> - <s>Change `#include "JuceHeader.h"` to `#include <JuceHeader.h>` everywhere, since that header isn't part of our local source for the purposes of a libopenshot build</s>

I actually didn't do that, this time. It's still a good idea, I just left it out of the changes in the new branch. Perhaps I'll add it in before merge.

> - Adjust all `CMakeLists.txt` files to account for new include path
> - Add an `examples/CMakeLists.txt`, and move the logic for compiling and installing the necessary components to that file
> - Add logic to `tests/CMakeLists`, `examples/CMakeLists`, `/CMakeLists.txt` so that build components are imported locally when needed
> - Update `Doxygen.in` file to build docs from new locations
> 
> This will be confusing, at first, when looking for moved files. (I've confused myself a couple of times already.) The relocated `bindings` directory is the one that throws me the most. But it really is _much_ simpler this way. Both in terms of humans editing the code, _and_ in terms of the contents of the code.
> 
> The reason `src/examples`, `src/Qt/demo`, and `src/bindings` got moved out of `src/` is in small part practical: If there are directories in `src/` without any installable headers, the `install(DIRECTORY...)` CMake command will end up creating empty directories in the output location. So, I wanted to avoid that.
> 
> But at the same time, the fact that that happens makes the point: _none_ of those directories' contents are part of the _libopenshot_ source code itself. So they really don't _belong_ in the **libopenshot** source dir. It makes more sense if they're separated.
> 
> The Doxygen docs mostly come out better, now. It never could follow the parent-relative `#includes`, so in the past _none_ of the source code listings' `#include`s linked to the header in question. Now almost all of them do, except for a few `#include "../foo.h"` statements in the `src/effects/` or `src/Qt` paths. (And in theory I could eliminate those using the include path, since `#include "ReaderBase.h"` should mean the same thing in `src/effects/Blur.h` that it means anywhere else. But I haven't tackled that for this PR, so it [still] uses `#include "../ReaderBase.h"`.)

In addition, enhancements are made to the build system:

1. `FindOpenShotAudio.cmake` now creates an `IMPORTED` target `OpenShot::Audio` to hold all of its configs. The configs are also still supplied in variables like `OpenShotAudio_INCLUDE_DIRS`, `OpenShotAudio_LIBRARIES`, etc., but the old `LIBOPENSHOT_AUDIO_INCLUDE_DIRS` and etc. variables are completely gone. The strongly recommended method of consuming the results of `find_package(OpenShotAudio)` is via the `OpenShot::Audio` `IMPORTED` target.

1. One reason `OpenShot::Audio` is preferred: that target (and _only_ the target) now incorporates _**all**_ of the additional/conditional build configuration relating to libopenshot-audio. This includes things like defining the `HAVE_ISFINITE` and `IGNORE_JUCE_HYPOT` macros, the extra DLL/framework linked into libopenshot on Win32 and MacOS platforms, and some compile options that need to be set in various scenarios. All of that logic used to be scattered around the various `CMakeLists.txt` files, but it's now all been consolidated as part of `FindOpenShotAudio.cmake`. The module exports all relevant configuration in the form of properties applied to the `OpenShot::Audio` target.

1. When `src/CMakeLists.txt` detects a successful `find_package(ImageMagick...)` check, it now  creates a target `ImageMagick::Magick++` and applies the necessary package configuration by setting properties on that target. (Actually, it creates a target `Magick++_TARGET`, then aliases `ImageMagick::Magick++` to that target. The "whys" of _that_ are nebulous, uninteresting, and best chalked up to "CMake nonsense" and left at that.) `target_link_libraries(openshot PUBLIC ImageMagick::Magick++)` then attaches all of that configuration to the libopenshot library build.

1. The reason for all of these newly-added targets is, it allows us to take advantage of automatic config propagation across the entire build system. Previously, `tests/CMakeLists.txt` had to duplicate some of the configuration from `src/CMakeLists.txt`, because non-target configs were limited to the `src/` directory (and subdirectory) context. And while the non-target configs were previously available to `src/bindings/*/CMakeLists.txt` as subdirectories of `src/` (and `src/examples/` was configured by `src/CMakeLists.txt`), now that those directories are moved out of `src/` and have their own `CMakeLists.txt` files that's no longer the case.

    CMake targets are global by definition, so any build configuration done in `src/CMakeLists.txt` **by means of target properties** will automatically be propagated to `tests/`, `bindings/` and `examples/` without the need for any redundant code. This makes the `CMakeLists.txt` files in those directories less complex, while at the same time making the overall build system more resilient and predictable since it's no longer possible for `CMakeLists.txt` inconsistencies to cause config changes from directory to directory.

    The now-redundant configuration previously being (re-)done in `tests/CMakeLists.txt` has been removed. (The sole exception to this is the optional DeckLink BlackMagic integration, which for the moment is still done via legacy non-target configs and therefore still has some minor duplication.)

A couple of other minor changes are also included: 

1. In testing `examples/Example.rb` I unearthed several bugs in our Ruby support, from code errors in that example file to build-configuration errors in `bindings/ruby/CMakeLists.txt`. This PR fixes all of those bugs, and after applying those fixes I was able to run `Example.rb` with Fedora's `ruby` command and have it display the image retrieved via `GetFrame()` as expected.

1. I renamed the `MappedMetadata` typedef to `MetadataMap` in the SWIG interface files, simply because it's the proper name based on the pattern established by the surrounding code. That change shouldn't affect any code, as those typedefs are only used in the generated SWIG code and aren't typically accessed directly. (The names are exported in the SWIG-generated bindings, though, so it's possible some code out there makes use of the bindings in some esoteric way that involves directly referencing the Python class `openshot.MappedMetadata`. If so, then the rename to `openshot.MetadataMap` breaks that code, and you have my apologies.)

### CODE REVIEW

**Comment by jonoomph** [comment]
@ferdnyc Not sure how this already has 2 conflicts, lol

**Comment by jonoomph** [comment]
If we are gonna do it... then let's go for it. As mentioned before, I don't have any strong opinions related to where header files live. I know convention is strong, and the include folder is a common pattern, but I do agree it makes things simpler to keep them together, and distribute them the same as we do now. I like it! Let's merge.

**Comment by jonoomph** [comment]
But I'll let you merge this one... so I can stand out of the blast radius. lol

**Comment by ferdnyc** [comment]
...WTH did I just do!?

**Comment by ferdnyc** [comment]
Well, that was fun. Managed to briefly wipe out the entire branch with a bad `git rebase --onto`. All fixed now, but the branch will have to regenerate. I'll merge as soon as all the builds succeed.

**Comment by ferdnyc** [comment]
All passed except the Gitlab Mac builder, which was stuck in previous jobs waiting on Apple. It's only just started building this branch now, but I'mma wait on it just to be _really_ sure.

**Comment by ferdnyc** [comment]
Huzzah! Here goes.... everything.

## Boom. :boom:

**Pull request merged**
