### PR TITLE
fix grammar error with possessive its and update sample for audio par…

### PR DESCRIPTION
**Pull request by ckirmse**
…ameter

Thank you for an awesome library! I just tried it yesterday for the first time and it worked nicely. The docs were missing an audio parameter which needs to be added in order for the sample code to work, and the incorrect grammar on some uses of it's vs its bugged me, so here are those fixes.

### CODE REVIEW

**Comment by jonoomph** [comment]
Sorry @ckirmse for the delay on this one. Can you please resolve any conflicts, and I'll be happy to take another looky and hopefully get this merged ASAP. You can also reach me at jonathan@openshot.org if you ever need to ping me.

**Comment by ckirmse** [comment]
no problem, this was my first essentially "test" PR from before the memory leak work :). Updated now and ready for review again.

**Comment by ferdnyc** [comment]
Looks good, thanks @ckirmse ! I just fixed a minor tabs-vs-spaces formatting issue in one of the headers, as soon as Travis gives the all-clear I'll merge this.

**Comment by ferdnyc** [comment]
Merging, zero-risk since all of the changes are in comments.

**Pull request merged**
