### PR TITLE
ImageMagick v7 patch

### PR DESCRIPTION
**Pull request by gary9872**
As per suggested here by Cauldron Ref to Issue #60

http://svnweb.mageia.org/packages/cauldron/libopenshot/current/SOURCES/libopenshot-0.1.8-fix-build-with-imagemagick7.patch?view=markup&pathrev=1218963

### CODE REVIEW

**Comment by peanutbutterandcrackers** [comment]
@gary9872 - Hey! So good to see your PR here, good sir! Hope @jonoomph will be able to review this, soon. :)

**Comment by jonoomph** [comment]
Looks good! How does this handle older versions of ImageMagick?

**Comment by RichiCoder1** [comment]
@jonoomph I'll test myself against an older version of ImageMagick as well as 7 here in a skip and a whop. IIRC correctly, these changes had to be made because of deprecations right? So in theory it should be compatible with 6 series (which I guess I'll find out).

**Comment by RichiCoder1** [comment]
Nope. This breaks for me when building against `mingw-w64-x86_64-imagemagick 6.9.3.7` from msys2. Builds properly and appears to work properly with `mingw-w64-x86_64-imagemagick 7.0.7`

**Comment by RichiCoder1** [comment]
Adding something like
```cmake
	add_definitions( -DIMAGEMAGICK_MAJOR_VERSION=${ImageMagick_VERSION_MAJOR} )
```

Near `add_definitions( -DUSE_IMAGEMAGICK=1 )`

And then `#ifdef IMAGEMAGICK_MAJOR_VERSION >= 7`

**Comment by RichiCoder1** [comment]
Adds backversion compat to this PR:

[0001-Added-version-compatibility.patch.zip](https://github.com/OpenShot/libopenshot/files/2027861/0001-Added-version-compatibility.patch.zip)

**Comment by RichiCoder1** [comment]
If @gary9872 doesn't jump on this by next week, I'll go ahead and submit an amended PR :)

**Comment by jonoomph** [comment]
Thanks @RichiCoder1! Let me know once there is a PR which incorporates these changes. =)

**Comment by jonoomph** [comment]
Closing this until someone updates with @RichiCoder1 's backward compatibility =)

**Pull request closed without merging**
