### PR TITLE
Add version/feature #defines to OpenShotVersion.h

### PR DESCRIPTION
**Pull request by ferdnyc**
The CMake process will pick up Qt's `Qt5Core_VERSION_STRING` variable and stick it in the CMake cache (with forced updating each run). A new `#define` in the header exports that as `QT_VERSION_STR` to both the library and the Python bindings. That way it can be queried at runtime, same as PyQt5's versioning:
```python3
>>> import openshot
>>> print(openshot.QT_VERSION_STR)
5.13.2
>>> from PyQt5 import Qt
>>> print(Qt.QT_VERSION_STR)
5.13.2
>>> print(Qt.PYQT_VERSION_STR)
5.13.2
```

**Edit:** I added a few more:
```python3
>>> openshot.AVUTIL_VERSION_STR
'56.31.100'
>>> openshot.AVCODEC_VERSION_STR
'58.54.100'
>>> openshot.AVFORMAT_VERSION_STR
'58.29.100'
>>> openshot.HAVE_IMAGEMAGICK
1
>>> openshot.HAVE_RESVG
1
```

**Edit2:** One more:
```python3
>>> openshot.APPIMAGE_BUILD
0
```
It's implemented as a CMake option, default `OFF` (hence the `0`). The Gitlab Linux runner will enable it (`cmake -DAPPIMAGE_BUILD=1`) when it generates the build environment.

I'll probably merge this soon, as it shouldn't affect any existing code and I'm going to have a need for that last one in an OpenShot PR shortly.

Inspired by https://github.com/OpenShot/openshot-qt/issues/3442#issuecomment-625206538

### CODE REVIEW

**Comment by ferdnyc** [comment]
I'm going to merge this, as it's inconsequential until it's made use of in the code. (And I have an impending need to make use of it.)

**Comment by jonoomph** [comment]
Looks like the Linux builder failed on this one:

```
Generating build files for OpenShot with CMake 3.7.2
  Building libopenshot (version 0.2.5)
  SO/API/ABI Version: 19

-- Found ImageMagick: /usr/lib/x86_64-linux-gnu/libMagick++.so  
-- Found OpenShotAudio: /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/install-x64/lib/libopenshot-audio.so (found suitable version "0.2.0-dev3", minimum required is "0.2.0") 
You have called ADD_LIBRARY for library openshot without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Using embedded jsoncpp (not found or USE_SYSTEM_JSONCPP disabled)
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- Checking for module 'libavcodec'
--   Found libavcodec, version 57.107.100
-- Checking for module 'libavdevice'
--   Found libavdevice, version 57.10.100
-- Checking for module 'libavformat'
--   Found libavformat, version 57.83.100
-- Checking for module 'libavfilter'
--   Found libavfilter, version 6.107.100
-- Checking for module 'libavutil'
--   Found libavutil, version 55.78.100
-- Checking for module 'libpostproc'
--   Found libpostproc, version 54.7.100
-- Checking for module 'libswscale'
--   Found libswscale, version 4.8.100
-- Checking for module 'libswresample'
--   Found libswresample, version 2.9.100
-- Checking for module 'libavresample'
--   Found libavresample, version 3.7.0
-- Found FFmpeg: /usr/lib/x86_64-linux-gnu/libavcodec.so;/usr/lib/x86_64-linux-gnu/libavdevice.so;/usr/lib/x86_64-linux-gnu/libavformat.so;/usr/lib/x86_64-linux-gnu/libavutil.so;/usr/lib/x86_64-linux-gnu/libswscale.so  
CMake Warning (dev) at src/CMakeLists.txt:306 (if):
  Policy CMP0057 is not set: Support new IN_LIST if() operator.  Run "cmake
  --help-policy CMP0057" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  IN_LIST will be interpreted as an operator when the policy is set to NEW.
  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at src/CMakeLists.txt:306 (if):
  if given arguments:

    "avcodec" "IN_LIST" "version_comps"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
See also "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/CMakeFiles/CMakeOutput.log".
ERROR: Job failed: exit status 1
```

**Comment by ferdnyc** [comment]
@jonoomph Gah!! Whoops. Lemme fix that...

**Comment by ferdnyc** [comment]
Fixed in #542.

**Pull request merged**
